### ISSUE TITLE
Clarify use of gcp API's not in default bootstrap set

### ISSUE THREAD

**Issue by winmillwill** [terraform-google-modules/terraform-example-foundation#10]
Thanks so much for putting together these examples! I've been having a blast blowing away and rebuilding my personal GCP infra, but I hit a snag on the way to building a GKE cluster:

I naively tried to create a `4-gke` directory and copied over and hacked variables and providers, and added an example from `terraform-google-modules/terraform-google-kubernetes-engine` but it seems like impersonating the terraform service account won't work unless the additional GCP APIs (in this case container.googleapis.com) are enabled in the project associated with that service account. I get an error like:

```
Error: googleapi: Error 403: Kubernetes Engine API has not been used in project ${SEED_PROJECT_ID} before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/container.googleapis.com/overview?project=${SEED_PROJECT_ID} then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry., accessNotConfigured
```

Is the idea that the seed project should enable every API that is enabled in every other project, and the GSA should have additional roles? Or should there be a separate terraform project with a full cloudbuild bootstrap and/or GSA for each different set of higher-level GCP API's?

**Comment by rjerrems** [comment]
Thanks for giving it a try @winmillwill - you are correct, if you are trying to use the same cloud build project as the other pipelines to build GKE it will need to have the APIs enabled.

Typically, we would create a cloudbuild project / pipeline which is more dedicated to application deployments - separate from the core foundations pipeline as it has a lot of powers. Would this be something you would be interested in seeing as an example added?

**Comment by winmillwill** [comment]
Yes, I would love an example like this. I appreciate the quick response!

**Comment by rjerrems** [comment]
Ok cool, right now we are focused on getting this fully released and documented. Once that is done, we can look at getting an example added.

**Comment by morgante** [comment]
> Is the idea that the seed project should enable every API that is enabled in every other project, and the GSA should have additional roles?

FYI this is usually what I'd do as a starting point. In more complicated setups, you can have multiple pipelines driven by multiple repos (with different service accounts).

**Comment by bharathkkb** [comment]
> Typically, we would create a cloudbuild project / pipeline which is more dedicated to application deployments - separate from the core foundations pipeline as it has a lot of powers. Would this be something you would be interested in seeing as an example added?

@rjerrems with our new approach for  and documentation in the SBP paper, I think this can be closed out?
