### ISSUE TITLE
Reconcile difference between naming networks in 3-networks and 4-projects

### ISSUE THREAD

**Issue by bharathkkb** [terraform-google-modules/terraform-example-foundation#104]
Currently 3-networks [define network name]( https://github.com/terraform-google-modules/terraform-example-foundation/blob/e61dbe3c76a081171938afe450675b2dc0ea65ed/3-networks/modules/standard_shared_vpc/main.tf#L31) as `network_name= vpc-${var.environment_code}-shared-${var.vpc_label}` where `vpc_label  = private|restricted`

 4-projects tries to [retrieve that network](https://github.com/terraform-google-modules/terraform-example-foundation/blob/e61dbe3c76a081171938afe450675b2dc0ea65ed/4-projects/modules/single_project/data.tf#L22) as  `name    = "${var.env_code}-shared-${var.vpc_type}"` where  `vpc_type = base|shared`

**Comment by daniel-cit** [comment]
I think we should chose the version of the names defined in 3-networks as it has the prefix `vpc-` and `vpc-d-shared-restricted` looks meaningful.

**Comment by rjerrems** [comment]
Fixed by https://github.com/terraform-google-modules/terraform-example-foundation/pull/93
