### ISSUE TITLE
Concurrent CI runs may fail due to multiple projects matching filter

### ISSUE THREAD

**Issue by bharathkkb** [terraform-google-modules/terraform-example-foundation#113]
Since projects maybe left over from failed runs or concurrent runs, it can match this filter (we only select the first matched project)
https://github.com/terraform-google-modules/terraform-example-foundation/blob/e61dbe3c76a081171938afe450675b2dc0ea65ed/3-networks/envs/dev/main.tf#L30
resulting in CI trying to put the project from the wrong build into the service perimeter and can result in errors. 
Possible example: https://console.cloud.google.com/cloud-build/builds/c6f63be0-c353-4539-854c-0ba760af56d0?project=cloud-foundation-cicd

**Comment by daniel-cit** [comment]
The search for the project could include the parent in the filter and find the parent folder for the environment using the organization or testing folder:

```
locals {
parent_id = var.parent_folder != "" ? "folders/${var.parent_folder}" : "organizations/${var.org_id}"
}

data "google_active_folder" "env" {
  display_name = local.env
  parent       = local.parent_id
}

data "google_projects" "restricted_host_project" {
  filter = "parent.id:${data.google_active_folder.env.name} labels.application_name=restricted-shared-vpc-host-${local.env} lifecycleState=ACTIVE"
}

```

**Comment by rjerrems** [comment]
Fixed by https://github.com/terraform-google-modules/terraform-example-foundation/pull/93
