### ISSUE TITLE
Readme adjustments: 0-bootstrap needs servicenetworking.googleapis.com enabled on bootstrap project

### ISSUE THREAD

**Issue by obriensystems** [terraform-google-modules/terraform-example-foundation#1136]
### TL;DR

Ongoing...
add a link to the tfvars for the following
https://github.com/terraform-google-modules/terraform-example-foundation/tree/master/0-bootstrap#prerequisites
```
Add the user who will use Terraform to the group_org_admins group. They must be in this group, or they won't have roles/resourcemanager.projectCreator access.
```
https://github.com/terraform-google-modules/terraform-example-foundation/blob/master/0-bootstrap/terraform.example.tfvars#L44

**Comment by fmichaelobrien** [comment]
0-bootstrap is up with the changes from #1133 to #1143
<img width="1397" alt="Screenshot 2024-03-07 at 10 12 58" src="https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/assets/24765473/c92ecd3d-f72d-4106-9fd4-801953156d13">

**Comment by fmichaelobrien** [comment]
stale bot timer restart - https://github.com/terraform-google-modules/terraform-example-foundation/blob/master/.github/workflows/stale.yml#L21

**Comment by fmichaelobrien** [comment]
fixed by
## PRs merged to the terraform-example-foundation upstream repo
- 20240426 https://github.com/terraform-google-modules/terraform-example-foundation/pull/1175
