### ISSUE TITLE
Dynamic terraform state backend using terragrunt

### ISSUE THREAD

**Issue by nhsy** [terraform-google-modules/terraform-example-foundation#114]
Great work all, with some terraform state automation using terragrunt it’ll make deployment  even easier without needing changes to backend.tf in each layer. 

An example below that demonstrates how to implement using terragrunt.hcl:
https://github.com/nhsy/terragrunt-gcp/blob/master/platform/terragrunt.hcl

**Comment by morgante** [comment]
Hi there!

Thanks for the suggestion. We're familiar with Terragrunt and agree it can definitely simplify things. However, we're also trying to keep this repo focused on vanilla Terraform.

You're welcome to add Terragrunt to a fork/local copy, but we probably won't add it to this example repo.
