### ISSUE TITLE
1-org - Should we move README out of envs/shared?

### ISSUE THREAD

**Issue by mikelaramie** [terraform-google-modules/terraform-example-foundation#115]
(this is for the `develop` branch)

The previous structure of this repo had the README files in the root area of each sub-repo; should we move README back to 1-org/ or leave it in 1-org/envs/shared?

**Comment by mikelaramie** [comment]
Also, need to add steps for copying tf-wrapper (once merged)

**Comment by daniel-cit** [comment]
> Also, need to add steps for copying tf-wrapper (once merged)

Pull request https://github.com/terraform-google-modules/terraform-example-foundation/pull/111 added instruction on copying the script in the Cloud Build section @mikelaramie

**Comment by daniel-cit** [comment]
I think we should leave the README in  `1-org/envs/shared` so that the automatic generation of the `input` and `output` from  terraform works.

**Comment by daniel-cit** [comment]
@mikelaramie Maybe  we could have two README.md files.

- One at `1-org` with the current README content minus the auto generated terraform input+ouptut
- One at `1-org/envs/shared` with only the auto generated terraform input+ouptut

**Comment by amandakarina** [comment]
> @mikelaramie Maybe we could have two README.md files.
> 
> * One at `1-org` with the current README content minus the auto generated terraform input+ouptut
> * One at `1-org/envs/shared` with only the auto generated terraform input+ouptut

Hey folks, I'll solve this issue following Daniel's suggestion, ok?

**Comment by mikelaramie** [comment]
Sounds good, and seems in-line with how we handled [3-networks](https://github.com/terraform-google-modules/terraform-example-foundation/tree/develop/3-networks)

**Comment by bharathkkb** [comment]
fixed via #163
