### ISSUE TITLE
upstream rebase and redeploy procedure/plan for changes since last CSR repos create

### ISSUE THREAD

**Issue by obriensystems** [terraform-google-modules/terraform-example-foundation#1150]
### TL;DR

Tracking changes since 20240306
https://github.com/terraform-google-modules/terraform-example-foundation/pull/1148/files

document a plan around managing the rebase into local CSR

### Terraform Configuration

```hcl
.
```

### Terraform Version

```sh
.
```

**Comment by fmichaelobrien** [comment]
stale bot timer restart - https://github.com/terraform-google-modules/terraform-example-foundation/blob/master/.github/workflows/stale.yml#L21
