### ISSUE TITLE
Eliminate hardcoding of assured-workloads in 2-environments/envs/production/main.tf

### ISSUE THREAD

**Issue by mromascanu123** [terraform-google-modules/terraform-example-foundation#1153]
### TL;DR

  module "env" {
    source = "../../modules/env_baseline"
	...
    assured_workload_configuration = {
       hardcoded enabled, compliance_regime and location 
	}   
  

### Detailed design

```markdown
Provide top-level configuration propagated to packages and modules or at least package top-level tfvars included by modules beneath
```

**Comment by fmichaelobrien** [comment]
stale bot timer restart - https://github.com/terraform-google-modules/terraform-example-foundation/blob/master/.github/workflows/stale.yml#L21

**Comment by sleighton2022** [comment]
Put as part of backlog for #1226
