### ISSUE TITLE
expand on docs for local terraform for bootstrap

### ISSUE THREAD

**Issue by obriensystems** [terraform-google-modules/terraform-example-foundation#1156]
### TL;DR

https://github.com/terraform-google-modules/terraform-example-foundation/tree/master/0-bootstrap#running-terraform-locally

Only parameters are discussed
at the same level as cloud build - for the case for where we run ADO for example
https://github.com/terraform-google-modules/terraform-example-foundation/tree/master/0-bootstrap#deploying-with-cloud-build

### Terraform Configuration

```hcl
.
```

### Terraform Version

```sh
.
```

**Comment by fmichaelobrien** [comment]
stale bot timer restart - https://github.com/terraform-google-modules/terraform-example-foundation/blob/master/.github/workflows/stale.yml#L21
