### ISSUE TITLE
2-environments - README updates

### ISSUE THREAD

**Issue by mikelaramie** [terraform-google-modules/terraform-example-foundation#117]
- Need to add steps to copy tf-wrapper.sh
- Step 5:  May not need to edit cloudbuild files with new logic?  Or describe how to modify regex to fit env names?
- Step 9:  Should we be pushing to `master` or `prod`?

**Comment by daniel-cit** [comment]
@mikelaramie I think that PR #111 fixes all these issues

**Comment by bharathkkb** [comment]
closed via #111
