### ISSUE TITLE
Correlate/Document FedRamp, NIST-800-53, ITSG-33 compliance in the TEF V4

### ISSUE THREAD

**Issue by fmichaelobrien** [terraform-google-modules/terraform-example-foundation#1173]
### TL;DR

see https://cloud.google.com/architecture/configure-networks-fedramp-dod-google-cloud

**Comment by mromascanu123** [comment]
From what I could see in the code so far, mechanisms for PGA, PSC and PSA seem to  be missing in TEF.

**Comment by fmichaelobrien** [comment]
stale bot timer restart - https://github.com/terraform-google-modules/terraform-example-foundation/blob/master/.github/workflows/stale.yml#L21
