### ISSUE TITLE
FR: add additional bidirectional link between the TEF and the CFT (Cloud Foundations Toolkit / terraform-blueprints) - like we have for the Enterprise Foundations Blueprint

### ISSUE THREAD

**Issue by obriensystems** [terraform-google-modules/terraform-example-foundation#1178]
### TL;DR

Add a link to the readme.md wrapping CFT references back to
- https://cloud.google.com/foundation-toolkit
- End-to-end, Operations = https://cloud.google.com/docs/terraform/blueprints/terraform-blueprints

as part of of overall architectural docs in 
#1177 

see https://github.com/terraform-google-modules/terraform-example-foundation?tab=readme-ov-file#terraform-example-foundation

**Comment by obriensystems** [comment]
all good

**Comment by fmichaelobrien** [comment]
in the root readme https://cloud.google.com/architecture/security-foundations
