### ISSUE TITLE
FR: add developer documentation around pull request submission and navigating the approval pipeline

### ISSUE THREAD

**Issue by obriensystems** [terraform-google-modules/terraform-example-foundation#1179]
### TL;DR

Add details around the procedures to get a PR approved to the readme in
https://github.com/terraform-google-modules/terraform-example-foundation/blob/master/CONTRIBUTING.md

specifically how to request review time from the https://github.com/terraform-google-modules/terraform-example-foundation/blob/master/CODEOWNERS

**Comment by fmichaelobrien** [comment]
stale bot timer restart - https://github.com/terraform-google-modules/terraform-example-foundation/blob/master/.github/workflows/stale.yml#L21
