### ISSUE TITLE
2-environments - Project Naming / Labels

### ISSUE THREAD

**Issue by mikelaramie** [terraform-google-modules/terraform-example-foundation#118]
- Need to update env-secrets and monitoring project names
- Need to remove environment from `application_name` label values (redundant with `environment` label value)

![image](https://user-images.githubusercontent.com/24661531/88462997-a6080a00-ce7d-11ea-8e49-ac59df2341c8.png)

**Comment by mikelaramie** [comment]
Also hit project creation quota on my SA when creating all 3 environments; we may want to add a warning about this.  Gonna try waiting an hour before finishing the prod build.

**Comment by bharathkkb** [comment]
@mikelaramie +1 i also hit this. Would be also nice to add some workarounds

**Comment by mikelaramie** [comment]
I ended up submitting a request for more project quota using this form: https://support.google.com/code/contact/project_quota_increase

**Comment by rjerrems** [comment]
Yep this is a known issue we should document clearly https://github.com/terraform-google-modules/terraform-example-foundation/issues/20

**Comment by rjerrems** [comment]
also, how old was the code you were running agains't - those org projects should have prj- at the front, they are only missing the p for prod

**Comment by daniel-cit** [comment]
@mikelaramie can we close this one?

**Comment by daniel-cit** [comment]
![image](https://user-images.githubusercontent.com/55760939/89074761-57fa7700-d353-11ea-8a5c-7750690f8311.png)

**Comment by mikelaramie** [comment]
lgtm
