### ISSUE TITLE
Run / debug locally with cloud-build-local

### ISSUE THREAD

**Issue by nhsy** [terraform-google-modules/terraform-example-foundation#122]
For a consistent SDLC cloud build can be run locally on your development workstation with the commands below:

cloud-build-local --config=[BUILD_CONFIG] --dryrun=false .

https://cloud.google.com/cloud-build/docs/build-debug-locally

This allows a more representative pipeline execution locally and faster feedback compared to running terraform init, terraform plan, etc.

**Comment by bharathkkb** [comment]
@nhsy were you by chance testing out the develop branch? One concern I have is that our [new approach](https://github.com/terraform-google-modules/terraform-example-foundation/blob/develop/build/cloudbuild-tf-apply.yaml) depends on `$BRANCH_NAME` which afaik wont be surfaced in `cloud-build-local` as there is no git trigger. We can probably work around this with substitutions.  

We have also abstracted some of the logic into[ a wrapper script](https://github.com/terraform-google-modules/terraform-example-foundation/blob/develop/build/tf-wrapper.sh) for ease of testing locally and ability to swap build systems as a first step.

**Comment by nhsy** [comment]
Sounds like a good plan.
