### ISSUE TITLE
2-networks - IP CIDR’s need parameterisation

### ISSUE THREAD

**Issue by nhsy** [terraform-google-modules/terraform-example-foundation#123]
All IP CIDR’s should be variables with sensible defaults. 

Happy to raise a PR if that helps.

**Comment by bharathkkb** [comment]
This sounds good to me. WDYT @rjerrems @daniel-cit

**Comment by rjerrems** [comment]
Is this on the master branch or develop @nhsy ? For context, we are nearing the end quite a few changes to the code base on develop.

Given this repo is a sample implementation, I would actually recommend we go in the opposite direction. For a module this type of behavior makes sense, but the intention for this repo is that teams will take it and customize it according to their own requirements.

Making these values variables with default values also makes it more difficult to read the code and understand exactly what is being created, as well as making it more rigid around a certain number of subnets etc (we actually used this approach on a previous version of the code)

**Comment by nhsy** [comment]
I was referring to the master branch, but the develop branch has the same issue. 

Terraform best practice is to customise deployment parameters using tfvars, instead of editing *.tf files directly. Default values do not make the code harder to read but is a fundamental feature of terraform.  

If the first step every team using this repo is to parameterise hard coded values then it’s inefficient and very short sighted devops approach.

**Comment by rjerrems** [comment]
Thanks for the feedback @nhsy - we will consider this in an
