### ISSUE TITLE
3-networks - README updates

### ISSUE THREAD

**Issue by mikelaramie** [terraform-google-modules/terraform-example-foundation#124]
Step 9:  Need to run `tf init` before `tf plan`

**Comment by mikelaramie** [comment]
Also the account running the tf manually needs the Service Account Token Creator role on the TF SA

**Comment by mikelaramie** [comment]
Do we want to recommend that they delete .terraform/ after running through the steps so it doesn't get checked in?  And/or add .terraform to .gitignore?

**Comment by bharathkkb** [comment]
we should add `.terraform` to `.gitignore` if not already.

**Comment by rjerrems** [comment]
the user should be in the org_admins group - this has service account token creator FYI @mikelaramie

**Comment by amandakarina** [comment]
PR merged
