### ISSUE TITLE
3-networks - errors implementing dns policy, managed zone

### ISSUE THREAD

**Issue by mikelaramie** [terraform-google-modules/terraform-example-foundation#126]
Troubleshooting the following errors

```
Error: Error creating Policy: googleapi: Error 403: Forbidden, forbidden                          

  on main.tf line 78, in resource "google_dns_policy" "default_policy":
  78: resource "google_dns_policy" "default_policy" {



Error: Error creating ManagedZone: googleapi: Error 403: Forbidden, forbidden                     

  on .terraform/modules/dns-forwarding-zone/terraform-google-cloud-dns-3.0.2/main.tf line 46, in resource "google_dns_managed_zone" "forwarding":
  46: resource "google_dns_managed_zone" "forwarding" {
```

**Comment by mikelaramie** [comment]
Looking at state, it appears that the script created the VPCs in a different DNS project (since multiple people are testing this in my org at once).  I wonder if we can scope the filter to parent?  I'll test it out

**Comment by mikelaramie** [comment]
I didn't have parent_folder set, which is probably causing some of my issues

**Comment by bharathkkb** [comment]
I added [the parent filter ](https://github.com/terraform-google-modules/terraform-example-foundation/blob/86893125ac5681f3d1f359f967f9cea11fd75ee7/3-networks/envs/shared/main.tf#L32) yesterday via #93  and I believe it should work even without `parent_folder` set with [this logic](https://github.com/terraform-google-modules/terraform-example-foundation/blob/86893125ac5681f3d1f359f967f9cea11fd75ee7/3-networks/envs/shared/main.tf#L20) on a fresh org.

**Comment by mikelaramie** [comment]
setting `parent_folder` got me through `envs/shared`, but now I'm hitting 

```
data.google_project.restricted_host_project: Refreshing state...

Error: Invalid index                                                                              

  on main.tf line 22, in locals:
  22:   private_project_id        = data.google_projects.private_host_project.projects[0].project_id
    |----------------
    | data.google_projects.private_host_project.projects is empty list of object

The given key does not identify an element in this collection value.
```
What is `private_host_project`?  I see a `base` and `restricted` host project created in 2-environments, but not a `private`

**Comment by jonathan-moulds-sb** [comment]
Hi @mikelaramie,

I think `private` and the `base` are one and the same. I originally thought `base` was something else but it seemed to pick up the `private` vpc details.

**Comment by mikelaramie** [comment]
That seems fair, @jonathan-moulds-sb - when I update the filter to search for "base" instead of "private", the code executes as expected.  I'll open a new issue to track.

**Comment by bharathkkb** [comment]
@mikelaramie I tried to change everything from `base` to `private` here #104. Lmk if we missed something.

**Comment by mikelaramie** [comment]
@bharathkkb Gotcha - I may have forgotten to do a pull before running it.  [This line](https://github.com/terraform-google-modules/terraform-example-foundation/blob/6fa24bd7cf39263d46767abbefc57c2ba01581ee/2-environments/modules/env_baseline/networking.tf#L42) is still tagging as "base" in my local files, which was causing the lookup to fail.

**Comment by rjerrems** [comment]
this should be closed now after that latest merge
