### ISSUE TITLE
3-networks - modification to filter for project/folder lookup

### ISSUE THREAD

**Issue by mikelaramie** [terraform-google-modules/terraform-example-foundation#127]
I had to update the [project filter](https://github.com/terraform-google-modules/terraform-example-foundation/blob/86893125ac5681f3d1f359f967f9cea11fd75ee7/3-networks/envs/prod/main.tf#L36)  for the data resources to use `element` in order for it to run successfully; not sure if this is an isolated issue in my environment or not, has anyone else run into this?

New filter:  `filter = "parent.id:${element(split("/", data.google_active_folder.env.name),1)} labels.application_name=restricted-shared-vpc-host-${local.env} lifecycleState=ACTIVE"`

**Comment by bharathkkb** [comment]
Hmm, this is odd. CI seems to be running fine and `element` and list access should [do the same thing](https://www.terraform.io/docs/configuration/functions/element.html) other than the wrap around behavior. Was this inside a cloud build or was this while running locally? If you have exact error that could be useful to narrow down.

**Comment by rjerrems** [comment]
Yeah if this is not in cloud build, would be good to know which terraform version you are using

**Comment by mikelaramie** [comment]
Locally I'm using 12.28, CB is using 12.24.  I didn't see it in CB because I didn't end up pushing it until I could get through a successful plan locally; but the TF error was that the google_projects data objects were returning an empty list.  I'll try and recreate it this morning, the error from last night is unfortunately lost to the ether

**Comment by daniel-cit** [comment]
@mikelaramie @rjerrems @bharathkkb Can we close this issue ?

**Comment by mikelaramie** [comment]
sgtm.  I'll reopen it if I hit it again since I'm the only one who seems to be hitting it.
