### ISSUE TITLE
3-networks - Update default DNS server IPs

### ISSUE THREAD

**Issue by mikelaramie** [terraform-google-modules/terraform-example-foundation#128]
In the [example tfvars](https://github.com/terraform-google-modules/terraform-example-foundation/blob/86893125ac5681f3d1f359f967f9cea11fd75ee7/3-networks/envs/shared/terraform.example.tfvars#L25), we use 8.8.8.4 as a secondary server; I believe this should be [8.8.4.4](https://developers.google.com/speed/public-dns/docs/using#addresses)

**Comment by rjerrems** [comment]
These are actually supposed to be IPs to forward queries on-prem, so it might make sense to make these example IPs come from RFC 1918 space
