### ISSUE TITLE
Example on how to implement 4-projects step for GitLab

### ISSUE THREAD

**Issue by KonStg** [terraform-google-modules/terraform-example-foundation#1285]
### TL;DR

There is an examples on how to implement all the foundation steps for GitLab in `0-bootstrap/envs/shared/README-GitLab.md` But nothing for infrastructure `4-projects` and `5-app-infra` steps.  
It would be very helpful for GitLab users to receive advice or direction for further actions in the phase `4-projects` when using CFT with GitLab.

**Comment by jalonsoa** [comment]
Hi !
  any news on this enhancement ? The 4-projects have the gitlab support in the pipeline, but the projects that create in this step don't have support for create resources in the 5-app-infra step with a gitlab pipeline ....
