### ISSUE TITLE
0-bootstrap - rename build triggers?

### ISSUE THREAD

**Issue by mikelaramie** [terraform-google-modules/terraform-example-foundation#129]
The build triggers created in `0-bootstrap` are still named `--terraform-apply-on-push-to-master` and `--terraform-plan-on-all-branches-except-master`, which are no longer indicative of their function (apply on push to dev|nonprod|prod, plan on push to anything else)

![image](https://user-images.githubusercontent.com/24661531/88497990-e657ad00-cf8f-11ea-8efe-33c7b43b9de1.png)

**Comment by rjerrems** [comment]
We should raise this bug on the bootstrap module, but good catch - should be easy to fix

**Comment by rjerrems** [comment]
I have opened a PR on bootstrap repo https://github.com/terraform-google-modules/terraform-google-bootstrap/pull/48

**Comment by daniel-cit** [comment]
@morgante should we keep this issue open until we have a new release of the bootstrap module and we can bump the version we are using?

**Comment by morgante** [comment]
@

**Comment by morgante** [comment]
Sure.

**Comment by rjerrems** [comment]
The module has been released now
