### ISSUE TITLE
4-projects - Provide example tfvars?

### ISSUE THREAD

**Issue by mikelaramie** [terraform-google-modules/terraform-example-foundation#130]
Should we provide an example tfvars for 4-projects projects?  Or is it safe to assume the user should know what to do at this point?

**Comment by rjerrems** [comment]
Yes, I think we should - I think we should have a symlinked tfvars file so you only need to add the variables in one place

**Comment by amandakarina** [comment]
Hey @rjerrems and @mikelaramie about the symlinked tfvars file, we have a variable called `perimeter_name` that have different values for each environment.

So, if we are going to create a symlinked tfvars file, this variable should be replaced by another 3 variables, for dev, nonprod and prod environment, for it to work.
