### ISSUE TITLE
Route scope tags preventing NAT egress from working for GKE autopilot

### ISSUE THREAD

**Issue by ajbeach2** [terraform-google-modules/terraform-example-foundation#1324]
### TL;DR

As written, the cloud foundation kit shared VPC does not work with private GKE cluster with NAT. After many hours of debugging:

https://github.com/terraform-google-modules/terraform-example-foundation/blob/5f1fd0f4104a47f8ce865caf3de3326f25c78324/3-networks-dual-svpc/modules/base_shared_vpc/main.tf#L46

This route scope tag prevents egress rules from applying. This needs to be be configurable at the module level so that NAT works with GKE autopiolot

**Comment by bdashrad** [comment]
I think I'm running into this myself, have an autopilot cluster in the shared VPC where the nodes can't reach the control plane

On apply I get:
`Error: Error waiting for creating GKE cluster: All cluster resources were brought up, but: only 0 nodes out of 1 have registered; cluster may be unhealthy.`

and I see firewall deny logs for `network:vpc-d-shared-base/firewallPolicy:fp-d-dual-svpc-base-firewalls` going from the nodes to the pool or google owned public IPs

**Comment by bdashrad** [comment]
I was able to get my autopilot cluster working by adding firewall rules following https://cloud.google.com/vpc-service-controls/docs/set-up-private-connectivity.
