### ISSUE TITLE
Jenkins: add conditional stage depending on if env branch

### ISSUE THREAD

**Issue by bharathkkb** [terraform-google-modules/terraform-example-foundation#147]
depends on #109 

Add [conditional stages](https://www.jenkins.io/doc/book/pipeline/syntax/#when) to Jenkinsfile such that
- if $BRANCH is an env branch (dev/prod/nonprod) do 4 stages - init, plan, validate, apply
- if $BRANCH is not an env branch (dev/prod/nonprod) do 1 stage -plan_validate_all

This will mirror current cloud build behavior.

**Comment by daniel-cit** [comment]
@bharathkkb can we close this one ?

**Comment by bharathkkb** [comment]
Yup fixed via #157
