### ISSUE TITLE
Clean up unused code in 4-projects 

### ISSUE THREAD

**Issue by daniel-cit** [terraform-google-modules/terraform-example-foundation#158]
(`develop`) Clean up unused code in 4-projects:

- Remove module `4-projects/modules/private_dns`
- Remove module `4-projects/modules/project_subnet`
- Remove `4-projects/backend.tf`
- Remove `4-projects/providers.tf`
- Remove `4-projects/variables.tf`
- Remove `4-projects/versions.tf`
- Update main README.md

**Comment by bharathkkb** [comment]
fixed via #164
