### ISSUE TITLE
Rename environment directories and branches to use long names

### ISSUE THREAD

**Issue by daniel-cit** [terraform-google-modules/terraform-example-foundation#184]
Rename environment directories (`dev`, `nonprod`, `prod`) and branches names (`dev`, `nonprod`, `prod`) to use long names (`development`, `non-production`, `production`)

Affects resources: 

- The repo file structure
- All README.md Instructions for 
  - Cloud Build
  - Jenkins
  - Manual deploy 
- The `tf-wrapper.sh` script
- `terraform_apply_branches` variable in `cloudbuild_bootstrap`
- The `Jenkinsfile`

**Comment by rjerrems** [comment]
Fixed by https://github.com/terraform-google-modules/terraform-example-foundation/pull/183
