### ISSUE TITLE
Use Passphrase to protect Jenkins ssh key

### ISSUE THREAD

**Issue by daniel-cit** [terraform-google-modules/terraform-example-foundation#192]
If the Jenkins ssh agent plugin allows for the usage of a Passphrase, using a Passphrase  should be the recommended instruction provided in the [Jenkins README](https://github.com/terraform-google-modules/terraform-example-foundation/blob/develop/0-bootstrap/README-Jenkins.md#i-setup-your-environment) in step `Generate a SSH key pair`

If it is not possible, an explanation should be  added explaining this limitation.

**Comment by caleonardo** [comment]
Thank you Daniel. I am creating the PR https://github.com/terraform-google-modules/terraform-example-foundation/pull/197
