### ISSUE TITLE
UX for new GCP organizations - Project Quota

### ISSUE THREAD

**Issue by winmillwill** [terraform-google-modules/terraform-example-foundation#20]
The default maximum number of projects with a billing account is 6, which is not high enough to follow the examples. It might be good to at least call that out, and maybe have a clear path to working around the limit, especially if some projects don't need a billing account and can be configured not to use one.

This seems to be the same root cause as the issue @morgante filed in terraform-providers/terraform-provider-google#1892 -- but that issue is closed, and the errors are still unclear. Are the examples pinned to a version of the provider that doesn't have the fix?

The error case is particularly bad UX because it manifests as inscrutable 400 errors on first apply, and then causes 409 errors afterward unless you either wipe the state completely or clear out the random suffix for the project id.

**Comment by rjerrems** [comment]
Thanks for the report @winmillwill , this is a common error and I think would be good to call out in the documentation.

If you would like to increase your project quota, you can submit a request via this form as an FYI

https://support.google.com/code/contact/project_quota_increase

**Comment by ipv1337** [comment]
> The default maximum number of projects with a billing account is 6, which is not high enough to follow the examples. It might be good to at least call that out, and maybe have a clear path to working around the limit, especially if some projects don't need a billing account and can be configured not to use one.
> 
> This seems to be the same root cause as the issue @morgante filed in [terraform-providers/terraform-provider-google#1892](https://github.com/terraform-providers/terraform-provider-google/issues/1892) -- but that issue is closed, and the errors are still unclear. Are the examples pinned to a version of the provider that doesn't have the fix?
> 
> The error case is particularly bad UX because it manifests as inscrutable 400 errors on first apply, and then causes 409 errors afterward unless you either wipe the state completely or clear out the random suffix for the project id.

Ran into this issue going through the instructions and was totally thrown off until I decided to check the issues. THANK YOU @winmillwill for pointing this out and saving me more hours of troubleshooting and thinking about tinkering with permissions which I would have HATED since the point of this was to stick with 100% Terraform automation. I'm trying to evaluate this for our company and this was a painful experience with the misleading error.

THANK YOU THANK YOU!

**Comment by bharathkkb** [comment]
added docs via #162
