### ISSUE TITLE
0-Bootstrap - Add instructions / configuration for Jenkins to use the GCS Bucket for artefacts in prj-cicd

### ISSUE THREAD

**Issue by caleonardo** [terraform-google-modules/terraform-example-foundation#211]
Include either instructions or (better) configuration in the Jenkinsfile to use the GCS Bucket for artefacts in `prj-cicd`
 - The Jenkins pipeline logs are currently created in the Jenkins Agent and can only be accessed there. We could use the  [Google Cloud Storage Plugin](https://github.com/jenkinsci/google-storage-plugin/blob/develop/docs/home.md) to copy those logs to the artefacts GCS Bucket.

**Comment by bharathkkb** [comment]
I think this is a great addition for next release. Ideally rather than instructions for the UI (to install the plugin) we should be using [jcac](https://www.jenkins.io/projects/jcasc/), but given the fact that we do not include a Jenkins master this is hard to automate.

**Comment by caleonardo** [comment]
I understand the GCS configuration can be added to the `Jenkinsfile` itself - see the "Pipeline examples" such as [this one](https://github.com/jenkinsci/google-storage-plugin/blob/develop/docs/home.md#pipeline-example)

In any case, we could also add the `jcac.yaml` file as an example? or at least, add a snippet of the jcac section where the GCS Bucket is configured?

**Comment by caleonardo** [comment]
BTW - An issue I saw with the GCS Plugin is that it only supports using Service Account credentials at the moment. So, it looks like the Master needs a Service Account (downloaded from GCP) and we don't want that. Instead, we want like plugin to use the SA assigned to the Jenkins Agent, without having to download a credential.

**Comment by bharathkkb** [comment]
@caleonardo 
> I understand the GCS configuration can be added to the Jenkinsfile itself

Yes but we will need instructions to say go to settings > install plugins, search for `Google Cloud Storage Plugin` etc. Also its hard to version pin when doing through UI.

> we could also add the jcac.yaml file as an example? 

Yeah, I think this is reasonable. Users can see the plugin dependencies transparently as we add some of these features.

> An issue I saw with the GCS Plugin is that it only supports using Service Account credentials

I thought it made use of the [Google OAuth Plugin](https://github.com/jenkinsci/google-oauth-plugin/blob/develop/docs/home.md#google-oauth-credentials) which works with metadata server on GCE.

**Comment by caleonardo** [comment]
@bharathkkb 
> I thought it made use of the [Google OAuth Plugin](https://github.com/jenkinsci/google-oauth-plugin/blob/develop/docs/home.md#google-oauth-credentials) which works with metadata server on GCE.

I understand this still requires to download the Service Account Key, which we want to avoid - Am I missing something? - I was expecting the GCS plugin to recognise the service account used by the GCE instance, the same way Terraform does.

Issue is that the Jenkins Master is not a GCE Instance, only the Agent is - so It is not clear to me how the Master can be configured, even if the job will be running in the Agent.
