### ISSUE TITLE
Migration path

### ISSUE THREAD

**Issue by fparga** [terraform-google-modules/terraform-example-foundation#218]
This is more of a question than an issue.

I am starting to provision an organization in GCP with Terraform using CFT modules. You just released a stable version `v0.1.0` of `terraform-example-foundation` but I notice that there is already a lot of changes between `master` and this version.

* For a new deployment, would you recommend starting with the version v0.1.0 or the one on master?
* Will you provide (or at least document) a migration path from the v0.1.0 to the next release?

**Comment by morgante** [comment]
Thanks for your interest.

> For a new deployment, would you recommend starting with the version v0.1.0 or the one on master?

We're in the process of finalizing the new release. I'd recommend starting with the new version as it's significantly more mature.

> Will you provide (or at least document) a migration path from the v0.1.0 to the next release?

This is not likely to be a priority for us. The intent with this example repo is different from the CFT modules (which we *do* provide upgrade guides for). Instead this repo is designed as a starting point which you should fork and modify to build your own Terraform footprint.

As such, while you are free to attempt upgrading yourself we will probably not be focusing on an upgrade path.

**Comment by fparga** [comment]
All right, thank you!
