### ISSUE TITLE
Update google_compute_firewall to use log_config

### ISSUE THREAD

**Issue by bharathkkb** [terraform-google-modules/terraform-example-foundation#221]
We should switch all `google_compute_firewall` to use `log_config` as `enable_logging` is being deprecated by TPG `3.33.0`.

ref: https://github.com/hashicorp/terraform-provider-google/pull/6871

**Comment by amandakarina** [comment]
Hey folks, about the metadata, in the compute firewall rules, we have two options: EXCLUDE_ALL_METADATA and INCLUDE_ALL_METADATA. Should we hard coded any of these options or the user should be able to choose (add new variable with default value)?
