### ISSUE TITLE
0-Bootstrap with Jenkins - Automate the VPN creation with Terraform

### ISSUE THREAD

**Issue by caleonardo** [terraform-google-modules/terraform-example-foundation#227]
When implementing the 0-Bootstrap step using Jenkins, it is necessary to configure a VPN connection between the `prj-cicd` project (where the Jenkins Agent lives) and <----> on-prem (or where ever the Jenkins Master lives). Here are the [instructions to configure the VPN connection](https://github.com/terraform-google-modules/terraform-example-foundation/blob/master/0-bootstrap/README-Jenkins.md#iii-create-vpn-connection), which basically require to run several `gcloud` commands (which is easier than providing UI instructions).

This issue is to track the implementation of terraform scripts to automate the VPN creation. 
- Most likely, this VPN configuration will live in the [jenkins-agent/main.tf](https://github.com/terraform-google-modules/terraform-example-foundation/blob/master/0-bootstrap/modules/jenkins-agent/main.tf) file.
- An example configuration is in [3-networks/modules/vpn-ha](https://github.com/terraform-google-modules/terraform-example-foundation/tree/master/3-networks/modules/vpn-ha)

**Comment by atos-cit** [comment]
Done in PR #234
