### ISSUE TITLE
build/Jenkinsfile - Automatically Populate Variables in Jenkinsfile

### ISSUE THREAD

**Issue by caleonardo** [terraform-google-modules/terraform-example-foundation#228]
Currently, we provide instructions (example for [1-org setup-to-run-via-jenkins](https://github.com/terraform-google-modules/terraform-example-foundation/tree/master/1-org#setup-to-run-via-jenkins)) to configure the [Jenkinsfile](https://github.com/terraform-google-modules/terraform-example-foundation/blob/master/build/Jenkinsfile), which include to set the following variables:
```
  environment {
    _POLICY_REPO=""
    _TF_SA_EMAIL=""
    _STATE_BUCKET_NAME=""
  }
```

This issue is about automating the configuration of the variables above in the Jenkinsfile. 
- One possible solution is to use metadata of the Jenkins Agent; use startup manager to read from metadata

**Comment by caleonardo** [comment]
See Storing and retrieving instance metadata: https://cloud.google.com/compute/docs/storing-retrieving-metadata

Possible solution:
**1 - Add metadata to the Jenkins Agent GCE Instance in [main.tf](https://github.com/terraform-google-modules/terraform-example-foundation/blob/master/0-bootstrap/modules/jenkins-agent/main.tf#L88):**
metadata = {
     jenkins_POLICY_REPO =""
    jenkins_TF_SA_EMAIL=""
    jenkins_STATE_BUCKET_NAME=""
  }

**2 - Change the [Jenkinsfile environments section](https://github.com/terraform-google-modules/terraform-example-foundation/blob/master/build/Jenkinsfile#L6) so environments variables are set [dynamically](https://www.jenkins.io/doc/book/pipeline/jenkinsfile/#setting-environment-variables-dynamically):**
 - Be aware to confirm what option to use: **returnStatus** or **returnStdout**. See more here: https://www.jenkins.io/doc/pipeline/steps/workflow-durable-task-step/
```
  environment {
    _POLICY_REPO="""${sh(
         returnStdout: true,
         script: 'curl "http://metadata.google.internal/computeMetadata/v1/instance/attributes/jenkins_POLICY_REPO" -H "Metadata-Flavor: Google"'
      )}"""

    _TF_SA_EMAIL="""${sh(
         returnStdout: true,
         script: 'curl "http://metadata.google.internal/computeMetadata/v1/instance/attributes/jenkins_TF_SA_EMAIL" -H "Metadata-Flavor: Google"'
      )}"""

    _STATE_BUCKET_NAME="""${sh(
         returnStdout: true,
         script: 'curl "http://metadata.google.internal/computeMetadata/v1/instance/attributes/jenkins_STATE_BUCKET_NAME" -H "Metadata-Flavor: Google"'
      )}"""
  }
```

**Comment by g-awmalik** [comment]
Closing since this is stale. Please reopen if necessary.
