### ISSUE TITLE
0-bootstrap - Error when reading or editing Organization Not Found: Error 403: The caller does not have permission, forbidden

### ISSUE THREAD

**Issue by horsey** [terraform-google-modules/terraform-example-foundation#229]
I am trying setup a baseline configuration using the example foundation module as a reference. 
I have an Organization user who has Owner and Oganization Administrator roles on the GCP project I am executing 'terraform-example-foundation'.
However,  I get the following error on `terraform apply': 

```
Error: Error when reading or editing Organization Not Found : <redacted-organization-id>: googleapi: Error 403: The caller does not have permission, forbidden

```
Steps to reproduce: 
```
gcloud auth login
cd 0-bootstrap
terraform apply

**Comment by rjerrems** [comment]
Hi @horsey - does your user have Organization Admin privileges at the Organization level? This is required to run the bootstrap. If you do, can you try the following:

```
gcloud auth application-default login
gcloud auth list ##confirm the correct account has a star next to it
```

Then re-run terraform?

**Comment by horsey** [comment]
@rjerrems Thank you. 
Running the commands
```
gcloud auth application-default login
gcloud auth list ##confirm the correct account has a star next to it
```
fixed the problem.  
Is this documented somewhere?

**Comment by bharathkkb** [comment]
Hi @horsey 
You can read more about using `application-default` credentials for Terraform [here](https://www.terraform.io/docs/providers/google/guides/provider_reference.html#credentials). The TL;DR is `gcloud auth login` lets you authenticate for gcloud. `gcloud auth application-default login` sets `Application Default Credentials` which can be automatically picked up GCP client libraries/ tools that uses those libraries, like Terraform.

We should definitely document this.

**Comment by horsey** [comment]
Hi @bharathkkb 
I had the project quite setup according to the README in this project and a few examples here: 

https://github.com/terraform-google-modules/terraform-google-bootstrap/tree/master/examples

It is the 
```
gcloud auth application-default login
``` 
that seems to be difference.
I have a few other issues with '0-bootstrap' . Can I continue this thread?

**Comment by rjerrems** [comment]
Hi @horsey - if its a separate issue, it would be preferable to raise a new bug if that is ok? If related to the issue above ^ happy to continue here

**Comment by rjerrems** [comment]
I think its probably worth documenting this more clearly @bharathkkb so perhaps we should keep this open until we add that to the bootstrap instructions?

**Comment by bharathkkb** [comment]
Yup that sgtm
