### ISSUE TITLE
Error: Error when reading or editing Resource  /  Error retrieving IAM policy

### ISSUE THREAD

**Issue by kbroughton** [terraform-google-modules/terraform-example-foundation#235]
I followed 0,1,2,3 and got stuck with project quota limits.
Starting up again once that was resolved a few days later, I got terraform errors that the shared-project had already been created. I presume this lack of idempotency is due to running gcloud scripts. 

I went back to 0-bootstrap and hit the issues reproduced below. I'm running with org role/owner, projectAdmin, billingAdmin superuser. As it was a few days later, i'm not 100% sure that some gcloud config settings weren't changed, but the docs don't mention anything in this regard.

Terraform v0.12.29

gcloud version
Google Cloud SDK 307.0.0
bq 2.0.59
core 2020.08.21
gsutil 4.53

git commit for terraform-example-foundation 0521aebc268f47fca (Aug 24)

```
module.seed_bootstrap.google_organization_iam_member.org_admins_group["roles/billing.user"]: Refreshing state... [id=$org_id/roles/billing.user/group:org-admins@example.net]

Error: Error when reading or editing Resource "folder \"folders/$folder_id\"" with IAM Member: Role "roles/resourcemanager.projectCreator" Member "group:org-admins@example.net": Error retrieving IAM policy for folder "folders/$folder_id": Post "https://cloudresourcemanager.googleapis.com/v2/folders/$folder_id:getIamPolicy?alt=json&prettyPrint=false": oauth2: cannot fetch token: 400 Bad Request
Response: {
  "error": "invalid_grant",
  "error_description": "reauth related error (invalid_rapt)",
  "error_subtype": "invalid_rapt"
}
```

I'm not 100% sure if this error is telling me that it is running as my superuser directly, or doing an "act-as" sort of thing for the group. But I granted org / folder viewer to the group to be sure and still get the error.

I don't suppose there's a support slack channel for this?

**Comment by kbroughton** [comment]
Ok, this was user error. During the wait for quotas, I must have tried another terraform-google project and over-written the application_default_credentials.json which a user is prompted to create on first terraform run. This wasn't mentioned in the docs so I had forgotten about it and assumed I was running with my `gcloud auth list` active user.

I was able to find the problem by running
TF_LOG=DEBUG terraform plan
which showed

Authenticating using DefaultClient...

which was enough to trigger my memory about the default credentials.

The check would be that either the default_credentials.json doesn't exist or the following returns crt-seed-<suffix>
cat ~/.config/gcloud/application_default_credentials.json | jq '.quota_project_id'
"cft-seed-<mysuffix>"

If you think it's worthwhile, I could make a README PR for this.

The fix was to delete the old and re-run
gcloud auth application-default login

**Comment by rjerrems** [comment]
Thanks for the report @kbroughton - I think we do need to make the docs clearer about setting up credentials if you are running the code locally. We have similar feedback in this issue https://github.com/terraform-google-modules/terraform-example-foundation/issues/229

FYI we do have some docs on the project quota issue [here](https://github.com/terraform-google-modules/terraform-example-foundation/tree/master/0-bootstrap#prerequisites), did you see those or discover yourself?

**Comment by kbroughton** [comment]
Thanks @rjerrems .  I think the trick for me was running the equivalent terraform as gcloud. The critical parts of the error message seem to get swallowed with terraform. I did come across the quota in 0 bootstrap later, but hadn't noticed it before. It only bit me in 3-networks.

**Comment by bharathkkb** [comment]
@kbroughton closing this in favor of #229 to track the local credentials documentation update. Also happy to accept a PR.
