### ISSUE TITLE
warn about expensive vpn-gateways / provide alternative

### ISSUE THREAD

**Issue by kbroughton** [terraform-google-modules/terraform-example-foundation#241]
This repo creates about 30 projects. It sets a billing alert for 1k, but the first alert is at 50%. It could be quite easy to accidentally run up a bill to $500 before noticing anything. I'd recommend
1. setting billing alerts that start at $10, $50, $100
2. offering a low-cost alternative to the VPN and Dedicated Interconnect

I use this repo for testing out migration recommendations to help secure customer accounts. I do not have a Dedicated Interconnect, so i chose the vpn option in 3-networks. However, this launches Gateways. Unlike nearly all the other infra in this repo, that can run up substantial bills in a short period of time. What would be a good alternative to the gateways? Would you consider an interim PR for docs that would adjust the default alerting downward and some short scripts to delete the VPN tunnels when the cluster is not in use?  Currently i'm doing it with gcloud cause I haven't done this sort of surgical deletion with tf before.

**Comment by rjerrems** [comment]
Thanks for the report @kbroughton - If you are not using the VPN right now, perhaps you can just comment out the code and destroy the VPN gateway / tunnels?

Also in terms of budgets, you should be able to override the budget amount and threshold by modifying the default for the variable, or overriding it in tfvars?

I think it would be worthwhile adding a warning note to the docs in terms of being wary of the cost of VPN and interconnect.
