### ISSUE TITLE
[devex] Improve data gathering per stage

### ISSUE THREAD

**Issue by bharathkkb** [terraform-google-modules/terraform-example-foundation#244]
At each stage, we ask the user to populate `terraform.tfvars` with values from previous stages or static data like `billing_account`. This seems like repeated data gathering and we should provide an alternative to automate/script some of this.

**Comment by morgante** [comment]
I have a module-based approach for dealing with this, will share an example PR.

**Comment by bharathkkb** [comment]
fixed by https://github.com/terraform-google-modules/terraform-example-foundation/pull/782. We still have a few places to fully make use of this but will track those separately.
