### ISSUE TITLE
[UX] Easily identify which build was triggered by commit

### ISSUE THREAD

**Issue by bharathkkb** [terraform-google-modules/terraform-example-foundation#245]
After each push, we need go to cloud console, find the build and watch logs via UI. This can can be alleviated by having a small script (`BUILD_ID=gcloud builds list --filter` and `gcloud builds log BUILD_ID --stream`) that streams logs or give url after a git push using hooks?

**Comment by g-awmalik** [comment]
@bharathkkb - are you still planning to work on this?

**Comment by bharathkkb** [comment]
Yeah lets keep in backlog
