### ISSUE TITLE
[shascanner] LOG_NOT_EXPORTED detected

### ISSUE THREAD

**Issue by amandakarina** [terraform-google-modules/terraform-example-foundation#258]
LOG_NOT_EXPORTED is detected because log sinks are created with 
    logName: /logs/cloudaudit.googleapis.com%2Factivity OR
    logName: /logs/cloudaudit.googleapis.com%2Fsystem_event OR
    logName: /logs/cloudaudit.googleapis.com%2Fdata_access OR
    logName: /logs/compute.googleapis.com%2Fvpc_flows OR
    logName: /logs/compute.googleapis.com%2Ffirewall OR
    logName: /logs/cloudaudit.googleapis.com%2Faccess_transparency

And the detector considers that the sink should have an empty filter to log every possible log created.

Changes sink creation to use a empty filter.

**Comment by rjerrems** [comment]
Can you elaborate further on the use case @amandakarina ? It seems like it will be costly/unnecessary to export multiple copies of all logs?

**Comment by bharathkkb** [comment]
@rjerrems its part of the things SHA scanner complained about during testing in Andy's org. I have tagged you in the doc and I think the reasoning was there were _some_ logs not being captured hence leading to it complaining.
