### ISSUE TITLE
Add a show command in tf-wrapper.sh

### ISSUE THREAD

**Issue by fparga** [terraform-google-modules/terraform-example-foundation#259]
Right now tf-wrapper.sh supports running the commands `init`, `plan`, `apply` and `validate`.

Validate makes a call to `terraform show` to output the plan as JSON for validation, however, there is no option to directly call `show` ourselves. 

Adding the show command would allow us to output the plan in a human-friendly format for inspection before merging on an environment branch. We could then post the output in a PR/MR comment for example.

What do you think?

**Comment by rjerrems** [comment]
Hi @fparga - this seems like a sensible option to include, I would be happy to accept a PR if you would like to add that function?

**Comment by fparga** [comment]
Sure, working on it!
