### ISSUE TITLE
1 - Org - Error creating project - Requested entity already exists

### ISSUE THREAD

**Issue by Marius-vog** [terraform-google-modules/terraform-example-foundation#265]
Hi, 
we are currently working our way through the terraform-example-foundation on our own organisation.

At 1 Org we ran into the error where there were to much projects linked to 1 billing account. We fixed that by requesting a higher quota. We then tried running the CI/CD pipeline (Cloud Build) again but we got this error:
![foundation-error](https://user-images.githubusercontent.com/43848342/96260042-bf24e080-0fbe-11eb-8be6-139d0e9927a1.PNG)

Somehow it doesnt recognize the projects that were already created in the previous step where it failed and now it can't create them because the project id already exists.

Can you help us?

Have a nice day!

**Comment by morgante** [comment]
Hi @Marius-vog! You'll have to [import](https://www.terraform.io/docs/providers/google/r/google_project.html#import) the existing projects:

```
terraform import module.org_secrets.module.project-factory.google_project.main prj-c-interconnect-8b4b
```

**Comment by Marius-vog** [comment]
Hi @morgante, thank you for your fast reply. 
We tried that in the cloud shell and got an authentication error because only the service account can change ressources: 
![image(3)](https://user-images.githubusercontent.com/43848342/96410942-fc1feb80-11e7-11eb-810d-3cf543c0d3ba.png)

**Comment by Marius-vog** [comment]
Alright we solved it. 
We did a terraform destroy and deleted everything from the 1-Org step. We ran into an error where it could not delete the "fldr-common" folder so we deleted the projects manually with the "--impersonate-service-account" flag. Then we did a terraform destroy again to delete the folder. 
We then could run the entired step 1-org again and the CI/CD build ran successfully.
