### ISSUE TITLE
Adds docs around possible billing quota issue

### ISSUE THREAD

**Issue by bharathkkb** [terraform-google-modules/terraform-example-foundation#269]
In addition to [project quota documented,](https://github.com/terraform-google-modules/terraform-example-foundation/tree/master/0-bootstrap#prerequisites) users may hit billing quota issue and it is surfaced with an error message like so
```
Error: Error setting billing account "<billing account id>" for project "projects/foo": googleapi: Error 400: Precondition check failed., failedPrecondition
```
To confirm if this is indeed the issue, we can manually try this
```
gcloud alpha billing projects link foo --billing-account XXXXXX-XXXXXX-XXXXXX
```
which will surface a quota issue and users have to request increase via https://support.google.com/code/contact/billing_quota_increase

x-ref: https://github.com/terraform-google-modules/terraform-google-project-factory/issues/28#issuecomment-422178737

**Comment by bharathkkb** [comment]
@daniel-cit if we are making a troubleshooting guide, this will be a good addition.

**Comment by rjerrems** [comment]
FYI we do currently have some docs here:

https://github.com/terraform-google-modules/terraform-example-foundation/tree/master/0-bootstrap#prerequisites

But we could make it more prominent / clearer how to check

**Comment by bharathkkb** [comment]
@rjerrems that is the project quota and the error surfaced is accurate. This in particular is about the billing quota (requires a different quota increase form) and the error is not very clear.

**Comment by rjerrems** [comment]
Aha cool, yeah worth documenting - I have never run into this before.
