### ISSUE TITLE
Add global prefix for created projects

### ISSUE THREAD

**Issue by bharathkkb** [terraform-google-modules/terraform-example-foundation#270]
As users are now deploying example-foundation, they will run into issues of reused project id's just like we do in CI. I propose we add a global prefix option, default to `""` and override default to `"test-"` for all of our CI tests. This will ensure less flakiness from reused project ids as well as give customers ability to add a prefix if needed.

**Comment by morgante** [comment]
I thought this was the original intent of the "prj-" part, which should definitely be replaced with a configurable value.

**Comment by bharathkkb** [comment]
@morgante currently it's hard coded to `prj-` but it should be relatively easy to reconfigure since we don't have any direct dependencies on the name itself.
