### ISSUE TITLE
Minor inconsistencies

### ISSUE THREAD

**Issue by umairidris** [terraform-google-modules/terraform-example-foundation#272]
There are a few inconsistencies in the example foundation which can lead to confusion:

- the environment 'common' and 'shared' are often mixed together, it should probably be one or the other
- the projects seem to follow pattern prj-${env_code}-${purpose} but the projects in the projects deployment don't follow this convention

**Comment by bharathkkb** [comment]
> the environment 'common' and 'shared' are often mixed together, it should probably be one or the other

Are there other instances of `common` apart from the `fldr-common` which is from the paper? We can probably rectify this in 2.0.

> the projects seem to follow pattern prj-${env_code}-${purpose} but the projects in the projects deployment don't follow this convention

In 4-projects we follow `prj-${var.business_code}-${local.env_code}-${var.project_prefix}` but its meant only as an example. The others like SVPC follow `prj-${var.environment_code}-shared-{base|restricted}`. Did you notice something outside of these conventions?

**Comment by umairidris** [comment]
1. I think the env code is 'c', if we use 'shared' as the only env then it probably should be 's'? That is the only thing I have seen so far.

2. I was looking at https://github.com/terraform-google-modules/terraform-example-foundation/blob/master/4-projects/business_unit_1/development/example_base_shared_vpc_project.tf#L31. Is that correct?

**Comment by umairidris** [comment]
Ah, please ignore point #2. I didn't realize it's the module that implements the naming convention! In this case this is just about ensuring we use the 'shared' env name everywhere including resource names and env codes.

**Comment by bharathkkb** [comment]
@umairidris got it, the shortnames seems to correspond with the paper where `common,prod,nonprod,dev` are `c,p,n,d` so we should rectify to either of those names (and short names) consistently.

**Comment by vovinacci** [comment]
@bharathkkb I could have renamed it to `shared` everywhere as we are doing it for ourselves anyway. Or is it better to stick to `common` as in the security foundations guide? What's your preferred option?
