### ISSUE TITLE
Convert BQ log destinations are configured to be partitioned

### ISSUE THREAD

**Issue by mikelaramie** [terraform-google-modules/terraform-example-foundation#273]
In the current code, we configure BQ log exports as sharded tables; we should modify this to create them as partitioned tables, which are more user-friendly and performant.

This fix can be implemented by adding the following to the `log_export_to_bigquery` [module](https://github.com/terraform-google-modules/terraform-example-foundation/blob/5c5b8b377494751cae70314976420ab04ddc5e55/1-org/envs/shared/log_sinks.tf#L41)

```
  bigquery_options       = {
    use_partitioned_tables  = true
  }
```

**Comment by rutalreja-deloitte** [comment]
@bharathkkb the update is already on the develop branch believe we can close the issue

**Comment by bharathkkb** [comment]
closed via https://github.com/terraform-google-modules/terraform-example-foundation/pull/277
