### ISSUE TITLE
Update log export GCS bucket to use object versioning

### ISSUE THREAD

**Issue by mikelaramie** [terraform-google-modules/terraform-example-foundation#274]
The storage bucket created by the `storage_destination` [module](https://github.com/terraform-google-modules/terraform-example-foundation/blob/5c5b8b377494751cae70314976420ab04ddc5e55/1-org/envs/shared/log_sinks.tf#L79) does not have [object versioning](https://cloud.google.com/storage/docs/object-versioning) enabled, which is generating a finding in SHA against the CIS Benchmark for GCP

This may require an update to the underlying `log-export` [module](https://github.com/terraform-google-modules/terraform-google-log-export/blob/master/modules/storage/main.tf) as it doesn't appear to be coded to accept a `versioning = true` setting.

**Comment by mikelaramie** [comment]
Additionally, the `bucket_policy_only` setting has been deprecated for `uniform_bucket_level_access` and should be updated accordingly in the `storage_destination` module

**Comment by mikelaramie** [comment]
Opened a related [issue](https://github.com/terraform-google-modules/terraform-google-log-export/issues/70) in the core `log-export` module

**Comment by vovinacci** [comment]
Opened PR to address this https://github.com/terraform-google-modules/terraform-google-log-export/pull/75

**Comment by bharathkkb** [comment]
closed via #317
