### ISSUE TITLE
[nit] env_baseline module has an unnecessary interpolation

### ISSUE THREAD

**Issue by mikelaramie** [terraform-google-modules/terraform-example-foundation#276]
Line 31 of [folders.tf](https://github.com/terraform-google-modules/terraform-example-foundation/blob/5c5b8b377494751cae70314976420ab04ddc5e55/2-environments/modules/env_baseline/folders.tf#L31) in the 2-environments/env_baseline module has an interpolation which is no longer necessary in tf 0.12+ and will throw a warning.

```
Warning: Interpolation-only expressions are deprecated

on ../../modules/env_baseline/folders.tf line 31, in resource "google_folder" "env":
31:   display_name = "${var.env}"
```

**Comment by vovinacci** [comment]
@mikelaramie @bharathkkb Wanted to resolve this one, but it seems that it's already been fixed. In the commit mentioned above, `develop` and `master` it's just fine.

```
display_name = "fldr-${var.env}"
```

Thanks!

**Comment by bharathkkb** [comment]
Yup it looks like its fine on main. @mikelaramie can you try the latest?
