### ISSUE TITLE
depriviledge vs deprivilege - what is the correct value

### ISSUE THREAD

**Issue by kumarvt** [terraform-google-modules/terraform-example-foundation#280]
default_service_account     = "depriviledge" should this be default_service_account     = "deprivilege" in files below?

https://github.com/terraform-google-modules/terraform-example-foundation/blob/7e8a34db7ee3e15d0265ebed7a5daf4b39309a29/2-environments/modules/env_baseline/secrets.tf

https://github.com/terraform-google-modules/terraform-example-foundation/blob/7e8a34db7ee3e15d0265ebed7a5daf4b39309a29/1-org/envs/shared/projects.tf

**Comment by bharathkkb** [comment]
@kumarvt Good catch, it should be `deprivilege`.
