### ISSUE TITLE
0-bootstrap: Error retrieving IAM policy for folder (forbidden)

### ISSUE THREAD

**Issue by vovinacci** [terraform-google-modules/terraform-example-foundation#284]
I haven't been able to apply `0-bootstrap` plan successfully.

Last three steps of `seed_bootstrap` module, related to SA impersonation failed:
```
  # module.seed_bootstrap.google_folder_iam_binding.project_creator[0] will be created
  + resource "google_folder_iam_binding" "project_creator" {
      + etag    = (known after apply)
      + folder  = "<org_id>"
      + id      = (known after apply)
      + members = [
          + "group:gcp-organization-admins@<domain.tld>",
          + "serviceAccount:org-terraform@cft-seed-<hash>.iam.gserviceaccount.com",
        ]
      + role    = "roles/resourcemanager.projectCreator"
    }

  # module.seed_bootstrap.google_folder_iam_member.org_admin_serviceusage_consumer[0] will be created
  + resource "google_folder_iam_member" "org_admin_serviceusage_consumer" {
      + etag   = (known after apply)
      + folder = "<org_id>"
      + id     = (known after apply)
      + member = "group:gcp-organization-admins@<domain.tld>"
      + role   = "roles/serviceusage.serviceUsageConsumer"
    }

  # module.seed_bootstrap.google_folder_iam_member.tmp_project_creator[0] will be created
  + resource "google_folder_iam_member" "tmp_project_creator" {
      + etag   = (known after apply)
      + folder = "<org_id>"
      + id     = (known after apply)
      + member = "group:gcp-organization-admins@<domain.tld>"
      + role   = "roles/resourcemanager.projectCreator"
    }

[ ... skip ... ]

module.seed_bootstrap.google_folder_iam_member.tmp_project_creator[0]: Creating...
module.seed_bootstrap.google_folder_iam_member.org_admin_serviceusage_consumer[0]: Creating...
module.seed_bootstrap.google_folder_iam_binding.project_creator[0]: Creating...

Error: Error retrieving IAM policy for folder "folders/<org_id>": googleapi: Error 403: The caller does not have permission, forbidden

Error: Error retrieving IAM policy for folder "folders/<org_id>": googleapi: Error 403: The caller does not have permission, forbidden

Error: Error retrieving IAM policy for folder "folders/<org_id>": gohttps://github.com/terraform-google-modules/terraform-example-foundation/blob/6f8a4c0a21aaad66e293e64306414baa924b04d3/0-bootstrap/main.tf#L92-L105ogleapi: Error 403: The caller does not have permission, forbidden
```

As per organisation IAM policies, `org-terraform@cft-seed-<hash>.iam.gserviceaccount.com` has the following roles attached
```
roles/accesscontextmanager.policyAdmin
roles/billing.user
roles/compute.networkAdmin
roles/compute.xpnAdmin
roles/iam.securityAdmin
roles/iam.serviceAccountAdmin
roles/logging.configWriter
roles/orgpolicy.policyAdmin
roles/resourcemanager.folderAdmin
roles/resourcemanager.organizationViewer
roles/resourcemanager.projectCreator
roles/securitycenter.notificationConfigEditor
```

and this correct according to the values set [here](https://github.com/terraform-google-modules/terraform-example-foundation/blob/6f8a4c0a21aaad66e293e64306414baa924b04d3/0-bootstrap/main.tf#L92-L105)

Terraform plugin versions:
```
$ jq -r 'keys[] as $k | "\($k) -> \(.[$k] | .version)"' .terraform/plugins/selections.json
registry.terraform.io/hashicorp/external -> 2.0.0
registry.terraform.io/hashicorp/google -> 3.46.0
registry.terraform.io/hashicorp/google-beta -> 3.46.0
registry.terraform.io/hashicorp/null -> 2.1.2
registry.terraform.io/hashicorp/random -> 2.3.1
```

I'm definitely missing something obvious, but cannot understand what exactly.
Your help would be highly appreciated.

**Comment by vovinacci** [comment]
@bharathkkb, @rjerrems @mikelaramie Sorry for pushing this a bit. This is holding back from taking further steps to migrate to GCP. If someone could take a look on this one, that would be very-very much appreciated!

**Comment by vovinacci** [comment]
Same behaviour with
```
registry.terraform.io/hashicorp/external -> 2.0.0
registry.terraform.io/hashicorp/google -> 3.47.0
registry.terraform.io/hashicorp/google-beta -> 3.47.0
registry.terraform.io/hashicorp/null -> 2.1.2
registry.terraform.io/hashicorp/random -> 2.3.1
```

**Comment by bharathkkb** [comment]
Hi @vovinacci 
Apologies for the delay, what are the roles on the user that you are using to run bootstrap. We have some requirements here: https://github.com/terraform-google-modules/terraform-example-foundation/tree/master/0-bootstrap#prerequisites

**Comment by vovinacci** [comment]
Hi @bharathkkb,
Many thanks for your reply.
Prerequisites
- A GCP Organization - ✔️ 
- A GCP Billing Account - ✔️ 
- Cloud Identity / G Suite groups for organization and billing admins - as per [checklist](https://console.cloud.google.com/getting-started/enterprise)
    - ✔️ Set up your Cloud Identity, domain and organisation resource - Account setup completed
    - ✔️ Add users and groups to your Cloud Identity account - Accounts for your administrator users created
    - ✔️ Set up administrator access to your organisation - Administrators given visibility and control
    - ✔️ Set up billing - Billing account and administrator access complete 
- Membership in the `group_org_admins` group for user running terraform - ✔️
- Grant the roles mentioned in bootstrap README.md, as well as `roles/resourcemanager.folderCreator` for the user running the step - ✔️ (even a bit more)
    ```
    roles/billing.admin
    roles/orgpolicy.policyAdmin
    roles/owner
    roles/resourcemanager.folderAdmin
    roles/resourcemanager.folderCreator
    roles/resourcemanager.organizationAdmin
    ```

Looks legit to me.

**Comment by mikelaramie** [comment]
@vovinacci To clarify, your account (or whichever account is showing as active if you run `gcloud auth list` on the system you're running `0-bootstrap` from) has those permissions?

Also, is the code actually trying to set 'folder = <org_id>', or is it showing a folder id?  If it's trying to do `folders/org_id`, that could be an issue as an org would start with `organizations/`

I'll also take a look and see if we missed anything in the roles listing.

**Comment by vovinacci** [comment]
@mikelaramie @bharathkkb Found it. In `module "seed_bootstrap"` `parent_folder` was set to `local.parent` instead of empty string (removed `parent_folder` variable to simplify the deployment and incorrectly evaluated resulting value).
I feel myself a bit stupid as this was very easy, but somehow got missed.
Thanks a lot for your kind help again!
