### ISSUE TITLE
create troubleshooting guide

### ISSUE THREAD

**Issue by bharathkkb** [terraform-google-modules/terraform-example-foundation#291]
Similar to [project factory](https://github.com/terraform-google-modules/terraform-google-project-factory/blob/master/docs/TROUBLESHOOTING.md) have a troubleshooting guide to debug common issues.
x-ref: https://github.com/terraform-google-modules/terraform-example-foundation/issues/269

**Comment by daniel-cit** [comment]
Guide created in https://github.com/terraform-google-modules/terraform-example-foundation/pull/466
