### ISSUE TITLE
Move hardcoded repos values to tfvars

### ISSUE THREAD

**Issue by konradclapa** [terraform-google-modules/terraform-example-foundation#292]
Hi Team, 

We would like to ask for a feature in the 0-boostrap stage. We would like to move the hardcoded array in
terraform-example-foundation/0-bootstrap/main.tf to variables. This would allow us to extend the landing zone easily. 

  cloud_source_repos = [
    "gcp-bootstrap",
    "gcp-org",
    "gcp-environments",
    "gcp-networks",
    "gcp-projects"
  ]

If you are ok with that request. We are happy to make a PR.

**Comment by rjerrems** [comment]
This makes sense to me, it may also make sense to have `terraform_apply_branches` as a variable.

@bharathkkb - WDYT?

**Comment by jaroslawgajewski** [comment]
I'd love to move all hardcoded values to default variables including projects, repos, labels etc

**Comment by bharathkkb** [comment]
SGTM
@jaroslawgajewski Happy to review if you also want to change `terraform_apply_branches` to a var in https://github.com/terraform-google-modules/terraform-example-foundation/pull/295
