### ISSUE TITLE
'gcp-bootstrap' repository and Cloud Build steps

### ISSUE THREAD

**Issue by vovinacci** [terraform-google-modules/terraform-example-foundation#293]
Hey, 

It seems that Cloud Source Repositories creation and associated Cloud Build tasks are also performed for [gcp-bootstrap](https://github.com/terraform-google-modules/terraform-example-foundation/blob/d6007d456ceb1b2ddf7e21a842ef5083bbe5586c/0-bootstrap/main.tf#L157) repository.

I am thinking if it could be removed from the list of repositories, as:

- It is not defined how to use it with Cloud Build in the documentation
- This is the initial step that most likely to be performed outside of the GCP (assuming that we start clean with new organisation)

Alternatively, usage guidelines on this repository could be added.

What do you think?

**Comment by rjerrems** [comment]
Hi @vovinacci - we have documented steps for using cloud build for stages 1-4, for example here https://github.com/terraform-google-modules/terraform-example-foundation/tree/master/1-org#setup-to-run-via-cloud-build

If there docs are unclear, it is certainly something we should look at fixing as that use case should be the default

**Comment by vovinacci** [comment]
@rjerrems Thank you very much for your reply.

I do completely agree that stages 1-4 are documented very well and no changes to be done there.

My question was more about step 0 - bootstrap. There is a Cloud Source Repository created for it and it's possible to run Cloud Build based on triggers.
As long as this stage is meant to be only once and it creates Cloud Build project itself as well as buckets, do we need to create Cloud Source Repository and triggers for it here https://github.com/terraform-google-modules/terraform-example-foundation/blob/d6007d456ceb1b2ddf7e21a842ef5083bbe5586c/0-bootstrap/main.tf#L157?

**Comment by rjerrems** [comment]
That is a good point @vovinacci - thanks for clarifying. I believe that repo / triggers were added with the intention of being able to run any future modifications via cloud build, but not tested or documented. The original use case for bootstrap was for it to be the one thing you run manually, to inflate the pipelines etc so it may be worthwhile considering removing the repo, or as you say adding support/docs for using cloudbuild for the case that you modify the code in the bootstrap phase.

@bharathkkb - what do you think?

**Comment by vovinacci** [comment]
@rjerrems @bharathkkb If there are no intentions to automate bootstrap run in the future, I would vote to remove it.

**Comment by jaroslawgajewski** [comment]
I'd go opposite way and extend documentation to fill bootstrap repository with code used to build it initially to for example introduce more flexibility there i.e. add additional CSRs etc

**Comment by rjerrems** [comment]
For now, we will remove until we have a better plan for its usage to avoid confusion for users.

**Comment by bharathkkb** [comment]
@rjerrems @vovinacci apologies, missed the original ping. My only concern is wouldn't we still need this stored in a repo if users want to change say for instance `org_project_creators`?

**Comment by rjerrems** [comment]
I think it would be good to have the bootstrap code in source control, but perhaps without the same triggers that are getting configured for the other repos. Alternatively we can do the work to add documentation / permissions so that it can be run by cloud build after the initial manual run, which would be ideal. 

If you think its a problem we can look at adding the repo back, its just confusing for end users in its current state. Perhaps something to plan for next release - WDYT?
