### ISSUE TITLE
Minor '3-networks' inconsistencies

### ISSUE THREAD

**Issue by vovinacci** [terraform-google-modules/terraform-example-foundation#294]
Few inconsistencies:

- In [3-networks/envs/development/main.tf](https://github.com/terraform-google-modules/terraform-example-foundation/blob/d6007d456ceb1b2ddf7e21a842ef5083bbe5586c/3-networks/envs/development/main.tf), projects data source is called [`base_project`](https://github.com/terraform-google-modules/terraform-example-foundation/blob/d6007d456ceb1b2ddf7e21a842ef5083bbe5586c/3-networks/envs/development/main.tf#L43), while other in environments it's called `base_host_project`([non-production](https://github.com/terraform-google-modules/terraform-example-foundation/blob/d6007d456ceb1b2ddf7e21a842ef5083bbe5586c/3-networks/envs/non-production/main.tf#L43), [production](https://github.com/terraform-google-modules/terraform-example-foundation/blob/d6007d456ceb1b2ddf7e21a842ef5083bbe5586c/3-networks/envs/production/main.tf#L43)). Should we make it `base_host_project` everywhere?
- In [3-networks/envs/development/main.tf](https://github.com/terraform-google-modules/terraform-example-foundation/blob/d6007d456ceb1b2ddf7e21a842ef5083bbe5586c/3-networks/envs/development/main.tf#L93-L103) and [3-networks/envs/production/main.tf](https://github.com/terraform-google-modules/terraform-example-foundation/blob/d6007d456ceb1b2ddf7e21a842ef5083bbe5586c/3-networks/envs/production/main.tf#L93-L103), when creating restricted shared VPC, secondary ranges use `default_region1`, while [3-networks/envs/non-production/main.tf](https://github.com/terraform-google-modules/terraform-example-foundation/blob/d6007d456ceb1b2ddf7e21a842ef5083bbe5586c/3-networks/envs/non-production/main.tf#L94-L104) use `default_region2`. Shall we use `default_region1` everywhere?
- In [3-networks/envs/development/main.tf](https://github.com/terraform-google-modules/terraform-example-foundation/blob/d6007d456ceb1b2ddf7e21a842ef5083bbe5586c/3-networks/envs/development/main.tf#108) comment states `Base shared VPC`, while for `non-production` and `production` it's `Private shared VPC`. Module name is `base_shared_vpc`. Shall we make comment consistent with the module name? Also, in `secondary_ranges` definition there, code style differs a bit.
- In all `variables.tf`, there's a typo [`Subnetwoks`](https://github.com/terraform-google-modules/terraform-example-foundation/blob/d6007d456ceb1b2ddf7e21a842ef5083bbe5586c/3-networks/envs/shared/variables.tf#L45).
- In `variables.tf` for `development`/`non-production`/`production` environments - there's a typo [`logginglogging`](https://github.com/terraform-google-modules/terraform-example-foundation/blob/d6007d456ceb1b2ddf7e21a842ef5083bbe5586c/3-networks/envs/production/variables.tf#L61).

If that all looks legit, I can create a PR to fix it. Thanks!

**Comment by rjerrems** [comment]
Thanks @vovinacci  - Most of these look good to me @bharathkkb - what do you think?
