### ISSUE TITLE
implement concurrent hub and spoke and default network integration tests 

### ISSUE THREAD

**Issue by bharathkkb** [terraform-google-modules/terraform-example-foundation#297]

**Comment by imrannayer** [comment]
@bharathkkb @averbuks Is there any reference architecture documentation for Hub Spoke? The official [Security Foundation Guidelines](https://services.google.com/fh/files/misc/google-cloud-security-foundations-guide.pdf) is showing simple architecture.

**Comment by bharathkkb** [comment]
Hi @imrannayer 
This will be part of the upcoming 2.0 release.

**Comment by imrannayer** [comment]
Thanks @bharathkkb. Is there an ETA for 2.0 release?
