### ISSUE TITLE
ERROR: (gcloud.alpha.scc.notifications.create) INTERNAL: Internal error encountered.

### ISSUE THREAD

**Issue by kumarvt** [terraform-google-modules/terraform-example-foundation#306]
I'm not able to get past this step in a new organisation. Not sure how to get past this error.

$ ./tf-wrapper.sh apply production
refs doesn't match production; skipping
objects doesn't match production; skipping
logs doesn't match production; skipping
info doesn't match production; skipping
hooks doesn't match production; skipping
branches doesn't match production; skipping
*************** TERRAFORM APPLY *******************
      At environment: envs/shared 
***************************************************
module.scc_notification.null_resource.run_command[0]: Destroying... [id=686037715437297042]
module.scc_notification.null_resource.run_command[0]: Destruction complete after 0s
module.log_export_to_storage.google_logging_organization_sink.sink[0]: Creating...
module.scc_notification.null_resource.run_command[0]: Creating...
module.log_export_to_pubsub.google_logging_organization_sink.sink[0]: Creating...
module.log_export_to_biqquery.google_logging_organization_sink.sink[0]: Creating...
module.interconnect.module.project-factory.google_project.main: Creating...
module.scc_notification.null_resource.run_command[0]: Provisioning with 'local-exec'...
module.scc_notification.null_resource.run_command[0] (local-exec): Executing: ["/bin/sh" "-c" "PATH=/gcp-org/envs/shared/.terraform/modules/scc_notification/cache/c1ebcc8b/google-cloud-sdk/bin:$PATH\ngcloud alpha scc notifications create scc-notify --organization 99999999999 \\\n--description \"SCC Notification for all active findings\" \\\n--pubsub-topic projects/prj-c-scc-8973/topics/top-scc-notification \\\n--filter \"state=\\\"ACTIVE\\\"\" \\\n--project \"prj-c-scc-8973\" \\\n--impersonate-service-account=org-terraform@cft-seed-9089.iam.gserviceaccount.com\n\n"]
module.scc_notification.null_resource.run_command[0] (local-exec): WARNING: This command is using service account impersonation. All API calls will be executed as [org-terraform@cft-seed-9089.iam.gserviceaccount.com].
module.scc_notification.null_resource.run_command[0] (local-exec): WARNING: This command is using service account impersonation. All API calls will be executed as [org-terraform@cft-seed-9089.iam.gserviceaccount.com].
module.scc_notification.null_resource.run_command[0]: Still creating... [10s elapsed]
module.scc_notification.null_resource.run_command[0]: Still creating... [20s elapsed]
module.scc_notification.null_resource.run_command[0]: Still creating... [30s elapsed]
module.scc_notification.null_resource.run_command[0]: Still creating... [40s elapsed]
module.scc_notification.null_resource.run_command[0] (local-exec): ERROR: (gcloud.alpha.scc.notifications.create) INTERNAL: Internal error encountered.

Error: Error running command 'PATH=/gcp-org/envs/shared/.terraform/modules/scc_notification/cache/c1ebcc8b/google-cloud-sdk/bin:$PATH
gcloud alpha scc notifications create scc-notify --organization 99999999999 \
--description "SCC Notification for all active findings" \
--pubsub-topic projects/prj-c-scc-8973/topics/top-scc-notification \
--filter "state=\"ACTIVE\"" \
--project "prj-c-scc-8973" \
--impersonate-service-account=org-terraform@cft-seed-9089.iam.gserviceaccount.com

': exit status 1. Output: WARNING: This command is using service account impersonation. All API calls will be executed as [org-terraform@cft-seed-9089.iam.gserviceaccount.com].
WARNING: This command is using service account impersonation. All API calls will be executed as [org-terraform@cft-seed-9089.iam.gserviceaccount.com].
ERROR: (gcloud.alpha.scc.notifications.create) INTERNAL: Internal error encountered.

Error: googleapi: Error 409: Sink sk-c-logging-pub already exists, alreadyExists

Error: googleapi: Error 409: Sink sk-c-logging-bq already exists, alreadyExists

Error: error creating project prj-c-interconnect-afb9 (prj-c-interconnect): googleapi: Error 409: Requested entity already exists, alreadyExists. If you received a 403 error, make sure you have the `roles/resourcemanager.projectCreator` permission

Error: googleapi: Error 409: Sink sk-c-logging-bkt already exists, alreadyExists

**Comment by rjerrems** [comment]
Hi @kumarvt - it looks like you are running into some issues with state where resources have already been created and trying to be recreated. Are you running this for the second time? What does your backend.tf look like?

**Comment by kumarvt** [comment]
Thank you @rjerrems for looking into this - I get this error first time as well as second time, then I destroyed everything and still was stuck on this step:

gcloud alpha scc notifications create scc-notify --organization 99999999999
--description "SCC Notification for all active findings"
--pubsub-topic projects/prj-c-scc-8973/topics/top-scc-notification
--filter "state="ACTIVE""
--project "prj-c-scc-8973"
--impersonate-service-account=org-terraform@cft-seed-9089.iam.gserviceaccount.com

This was only resolved when I enabled Security Control center from using GCP console manually. It appears that this step is missing from the instructions.

**Comment by rjerrems** [comment]
Thanks for sharing @kumarvt - I will leave this bug open to track documenting that better.

FYI @bharathkkb

**Comment by markusvanlaak** [comment]
@kumarvt What have you exactly enabled. Still running into the error after enabling SCC in my prj-c-scc-XXX.

**Comment by markusvanlaak** [comment]
The errors I get are

> module.scc_notification.null_resource.run_command[0] (local-exec): ERROR: (gcloud.alpha.scc.notifications.create) INTERNAL: Internal error encountered.


Error: Error updating Budget "billingAccounts/01B01C-60BA4B-7EDE1D/budgets/4ed10829-c0d9-4aa6-8be9-0dbde66e13f4": googleapi: Error 400: Request contains an invalid argument.



Error: Error updating Budget "billingAccounts/01B01C-60BA4B-7EDE1D/budgets/983e0f07-597c-4b0e-8820-08e17ef51475": googleapi: Error 400: Request contains an invalid argument.



Error: Error updating Budget "billingAccounts/01B01C-60BA4B-7EDE1D/budgets/d93824b5-83c9-48cd-9507-d368e17eb263": googleapi: Error 400: Request contains an invalid argument.



Error: Error updating Budget "billingAccounts/01B01C-60BA4B-7EDE1D/budgets/cc33a831-bd6d-4b9f-b301-509ce04036a9": googleapi: Error 400: Request contains an invalid argument.



Error: Error running command 'PATH=/usr/local/home/vl/gcp-org/envs/shared/.terraform/modules/scc_notification/cache/45624f1a/google-cloud-sdk/bin:$PATH
gcloud alpha scc notifications create scc-notify --organization 253569058545 \
--description "SCC Notification for all active findings" \
--pubsub-topic projects/prj-c-scc-72e6/topics/top-scc-notification \
--filter "state=\"ACTIVE\"" \
--project "prj-c-scc-72e6" \
--impersonate-service-account=org-terraform@cft-seed-f169.iam.gserviceaccount.com

': exit status 1. Output: WARNING: This command is using service account impersonation. All API calls will be executed as [org-terraform@cft-seed-f169.iam.gserviceaccount.com].
WARNING: This command is using service account impersonation. All API calls will be executed as [org-terraform@cft-seed-f169.iam.gserviceaccount.com].
ERROR: (gcloud.alpha.scc.notifications.create) INTERNAL: Internal error encountered.




Error: Error updating Budget "billingAccounts/01B01C-60BA4B-7EDE1D/budgets/e533cec1-633b-4158-966b-214981fbac4a": googleapi: Error 400: Request contains an invalid argument.



Error: Error updating Budget "billingAccounts/01B01C-60BA4B-7EDE1D/budgets/5aae3735-25ee-4d60-9377-37755776483a": googleapi: Error 400: Request contains an invalid argument.

**Comment by bharathkkb** [comment]
Hi @markusvanlaak 
This seems like a provider issue being tracked here https://github.com/hashicorp/terraform-provider-google/issues/8241
