### ISSUE TITLE
Storage bucket does not exist.

### ISSUE THREAD

**Issue by sbadakhc** [terraform-google-modules/terraform-example-foundation#31]
Hi,

I'm following the instructions for the 0-bootstrap and executing terraform init is reporting the following error. 
```
Initializing the backend...

Successfully configured the backend "gcs"! Terraform will automatically
use this backend unless the backend configuration changes.

Error: Failed to get existing workspaces: querying Cloud Storage failed: storage: bucket doesn't exist
```

I tried to remove the .terraform dir and terraform init -reconfigure but the error persists.

I'm using Terraform v0.12.24.

Thanks.

**Comment by rjerrems** [comment]
Thanks for the report @sbadakhc - did you rename `backend.tf.example` before running terraform init? If so, you should rename it to original name until after you have run through the steps to apply the terraform as the terraform state for this step should be generated locally first.

**Comment by sbadakhc** [comment]
Thanks @rjerrems  - I will try this and feedback shortly.
