### ISSUE TITLE
Pin peering module version in networks

### ISSUE THREAD

**Issue by konradclapa** [terraform-google-modules/terraform-example-foundation#313]
We have noticed an issue with running the Example Deployment on Terraform 0.12
 
We see that the latest CFT peering module is already using 0.13 version and it fails on 0.12
 
 
Template path /terraform-example-foundation/4-projects/business_unit_1/production/example_peering_project.tf
Module failing: module "peering" (line 66)
 
As you don’t specify the version of the peering module, the latest one is used and it is not compatible with 0.12

The workaround used: added line with version 2.6.0 of the terraform-google-modules/network modules

**Comment by bharathkkb** [comment]
Thanks for the issue @konradclapa 
We will fix this is as part of the 2.0 release which will introduce 0.13 support as well.

**Comment by rjerrems** [comment]
FYI @konradclapa this should be fixed for terraform v0.12 in the latest release/on master - we will pin to a newer version of the module in the v2 release.

**Comment by daniel-cit** [comment]
Fixed by https://github.com/terraform-google-modules/terraform-example-foundation/pull/384
