### ISSUE TITLE
guidance needed

### ISSUE THREAD

**Issue by mbghdev** [terraform-google-modules/terraform-example-foundation#314]
Hello, 

_disclaimer: I didn't find a specific place to ask this so I'll just do it here and if it isn't the place, apologies and may I ask to point me towards the correct place, thanks!_

I've successfully deployed the CFT w/TF v 0.12. I've got the BU1 & 2 projects with the dev environment ready.

Now I'd like to test it out: In order to do this I've created a new GCE instance in BU1. I saw that it grabbed an IP from the **sb-d-shared-base-us-central1** subnet in **prj-d-shared-base** shared-VPC. So far so good.

Inside this VM, I installed apache2 with the startup script. I'd like to make this webserver available to internet.
My idea is to keep aligned with the best practices, therefore I would like to ask: 

1. where do I need to request the public IP address? 
2. I'm guessing I'll need to create a firewall rule for the egress traffic, should I add it in TF?
3. do I need to add a label to the VM in order to make the port 80 accessible from the internet?
4. I'm pretty sure I'm missing things to be done, please let me know

Thanks in advance and great repositories/explanations!

**Comment by bharathkkb** [comment]
Hi @mbghdev 
I have answered questions inline below.

> where do I need to request the public IP address?

You can use `google_compute_address` within your GCE Terraform config to reserve an external IP address. [Here](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_address#example-usage---instance-with-ip) is an example

> I'm guessing I'll need to create a firewall rule for the egress traffic, should I add it in TF?

It is recommended to manage it via TF using `google_compute_firewall` resource. You can [override](https://cloud.google.com/vpc/docs/firewalls#priority_order_for_firewall_rules) the created `deny_all_egress` within the specific env for instance [dev](https://github.com/terraform-google-modules/terraform-example-foundation/blob/master/3-networks/envs/development/main.tf) network config

> do I need to add a label to the VM in order to make the port 80 accessible from the internet?

You can create a FW rule to allow ingress from `0.0.0.0/0` on port 80 and target this FW rule via a label or a service account. There is some additional [guidance](https://cloud.google.com/vpc/docs/firewalls#service-accounts-vs-tags) here.

**Comment by mbghdev** [comment]
_I have literally 1 month w/TF and GCP so I'm asking quite a few newbie Q's, thanks in advance for your help @bharathkkb_ 

I'll be checking those points, thanks.

Meanwhile, I tried to generate a GKE cluster while leveraging the _project-factory_ module + _terraform-google-kubernetes-engine_ (which I've cloned and then commited to the gcp-projects repo).

I enabled the gke api in seed project, in prj-d-shared-base and the newly created project prj-bu1-d-gke01

I've read in GCP's documentation that the GKE's SA must be added to the host SVPC project. Therefore:
```
module "service_account-iam-bindings-gke" {
  source = "terraform-google-modules/iam/google//modules/service_accounts_iam"
  service_accounts = [
    "serviceAccount:${module.gke.service_account}"
  ]
  project          = module.gke.network_project_id
  mode             = "additive"
  bindings = {
    "roles/compute.networkUser" = [
      "serviceAccount:${module.gke.service_account}"
    ]
    "roles/container.hostServiceAgentUser" = [
      "serviceAccount:${module.gke.service_account}"
    ]
  }
```


Here's the GKE module part
```
module "gke" {
  source                      = "./gke-private-cluster/"
  project_id                  = module.project.project_id  # ID from the project created with project-factory for GKE
  network                     = "vpc-d-shared-base"
  network_project_id          = "prj-d-shared-base-xxxx"
}
```

Here's the result:
`Error: "service_account_id" ("projects/prj-d-shared-base-xxxx/serviceAccounts/serviceAccount:tf-gke-gke-bu1-d-clust-xxxx@prj-bu1-d-gke01-xxxx.iam.gserviceaccount.com") doesn't match regexp "projects/(?:(?:[-a-z0-9]{1,63}\\.)*(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?):)?(?:[0-9]{1,19}|(?:[a-z0-9](?:[-a-z0-9]{0,61}[a-z0-9])?)|-)/serviceAccounts/((?:(?:[-a-z0-9]{1,63}\\.)*(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?):)?(?:[0-9]{1,19}|(?:[a-z0-9](?:[-a-z0-9]{0,61}[a-z0-9])?))@[a-z]+.gserviceaccount.com$|[0-9]{1,20}-compute@developer.gserviceaccount.com|[a-z](?:[-a-z0-9]{4,28}[a-z0-9])@[-a-z0-9\\.]{1,63}\\.iam\\.gserviceaccount\\.com$)"`

I do have the #######-compute@developer.gserviceaccount.com Compute Engine default service account which is disabled (I'm guessing project-factory did that). Am I missing a step where the compute account is generated?

Thanks again,

PS: I search but didn't find this issue and preferred to ask here. Let me know if I should open a new issue for this or it's OK.
Thanks!
