### ISSUE TITLE
[UX] `cp -RT` is not portable

### ISSUE THREAD

**Issue by juliocc** [terraform-google-modules/terraform-example-foundation#330]
Going through the instructions there are multiple instances of `cp -RT`. The option -T (--no-target-directory) is GNU specific and fails, for example, in macOS.

**Comment by renato-rudnicki** [comment]
@bharathkkb Should we update all READMEs with a separate version of `cp` command for Linux and Mac OS? Or do you think it is be better we mention it in only one README saying the `cp` commando for Linux and Mac OS should be used for the next instructions?

**Comment by rjerrems** [comment]
Which version of macOS did you run into this on @juliocc? I just tested on `10.15.7` and it seems to be fine / support those arguments looking at the man pages.

**Comment by bharathkkb** [comment]
@renato-rudnicki I think we should create a section in the troubleshooting guide for this explaining the difference. Within all readmes we can then say `Copy contents of foundation to new repo. Command may vary with platform.` and link the doc section.

**Comment by mark1000** [comment]
What would the command be for other OSs?

**Comment by mark1000** [comment]
MacOS: cp -R

**Comment by bharathkkb** [comment]
fixes https://github.com/terraform-google-modules/terraform-example-foundation/pull/515
