### ISSUE TITLE
Error while executing the CloudBuild steps for 1-org in Googles  terraform-example-foundation

### ISSUE THREAD

**Issue by Suhasth02** [terraform-google-modules/terraform-example-foundation#332]
Hi,

I am need to step up **1-org** form **terraform-example-foundation** I am  following steps mentioned at link - https://github.com/terraform-google-modules/terraform-example-foundation/tree/master/1-org

We have used the appropriate service account in this scneario.

1. Clone repo gcloud source repos clone gcp-org --project=YOUR_CLOUD_BUILD_PROJECT_ID (this is from terraform output from the previous section, 0-bootstrap).

2. Navigate into the repo cd gcp-org and change to a non production branch git checkout -b plan

3. Copy contents of foundation to new repo cp -RT ../terraform-example-foundation/1-org/ . (modify accordingly based on your current directory).

4. Copy cloud build configuration files for terraform cp ../terraform-example-foundation/build/cloudbuild-tf-* . (modify accordingly based on your current directory).

5. Copy terraform wrapper script cp ../terraform-example-foundation/build/tf-wrapper.sh . to the root of your new repository (modify accordingly based on your current directory).

6. Ensure wrapper script can be executed chmod 755 ./tf-wrapper.sh.

7. Check if your organization already has a Access Context Manager Policy gcloud access-context-manager policies list --organization YOUR-ORGANIZATION_ID --format="value(name)".

8. Rename ./envs/shared/terraform.example.tfvars to ./envs/shared/terraform.tfvars and update the file with values from your environment and bootstrap (you can re-run terraform output in the 0-bootstrap directory to find these values). Make sure that default_region is set to a valid BigQuery dataset region. Also if the previous step showed a numeric value, make sure to un-comment the variable create_access_context_manager_access_policy = false.

9. Commit changes with git add . and git commit -m 'Your message'

10. Push your plan branch to trigger a plan git push --set-upstream origin plan (the branch plan is not a special one. Any branch which name is different from development, non-production or production will trigger a terraform plan).
Review the plan output in your cloud build project https://console.cloud.google.com/cloud-build/builds?project=YOUR_CLOUD_BUILD_PROJECT_ID

**I am getting below errors in GCP cloud build** 

Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": This value does not have any attributes.
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all":     | google_service_account.default_service_account is empty tuple
Step #1 - "tf plan validate all":     |----------------
Step #1 - "tf plan validate all":   59:   value       = google_service_account.default_service_account.unique_id
Step #1 - "tf plan validate all":   on .terraform/modules/scc_notifications/modules/core_project_factory/outputs.tf line 59, in output "service_account_unique_id":
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": Error: Unsupported attribute
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": This value does not have any attributes.
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all":     | google_service_account.default_service_account is empty tuple
Step #1 - "tf plan validate all":     |----------------
Step #1 - "tf plan validate all":   54:   value       = google_service_account.default_service_account.name
Step #1 - "tf plan validate all":   on .terraform/modules/scc_notifications/modules/core_project_factory/outputs.tf line 54, in output "service_account_name":
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": Error: Unsupported attribute
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": This value does not have any attributes.
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all":     | google_service_account.default_service_account is empty tuple
Step #1 - "tf plan validate all":     |----------------
Step #1 - "tf plan validate all":   49:   value       = google_service_account.default_service_account.email
Step #1 - "tf plan validate all":   on .terraform/modules/scc_notifications/modules/core_project_factory/outputs.tf line 49, in output "service_account_email":
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": Error: Unsupported attribute
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": This value does not have any attributes.
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all":     | google_service_account.default_service_account is empty tuple
Step #1 - "tf plan validate all":     |----------------
Step #1 - "tf plan validate all":   44:   value       = google_service_account.default_service_account.display_name
Step #1 - "tf plan validate all":   on .terraform/modules/scc_notifications/modules/core_project_factory/outputs.tf line 44, in output "service_account_display_name":
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": Error: Unsupported attribute
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": This value does not have any attributes.
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all":     | google_service_account.default_service_account is empty tuple
Step #1 - "tf plan validate all":     |----------------
Step #1 - "tf plan validate all":   39:   value       = google_service_account.default_service_account.account_id
Step #1 - "tf plan validate all":   on .terraform/modules/scc_notifications/modules/core_project_factory/outputs.tf line 39, in output "service_account_id":
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": Error: Unsupported attribute
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": This value does not have any attributes.
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all":     | google_service_account.default_service_account is empty tuple
Step #1 - "tf plan validate all":     |----------------
Step #1 - "tf plan validate all":   39:     google_service_account.default_service_account.email,
Step #1 - "tf plan validate all":   on .terraform/modules/scc_notifications/modules/core_project_factory/main.tf line 39, in locals:
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": Error: Unsupported attribute
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": This value does not have any attributes.
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all":     | google_service_account.default_service_account is empty tuple
Step #1 - "tf plan validate all":     |----------------
Step #1 - "tf plan validate all":   59:   value       = google_service_account.default_service_account.unique_id
Step #1 - "tf plan validate all":   on .terraform/modules/org_secrets/modules/core_project_factory/outputs.tf line 59, in output "service_account_unique_id":
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": Error: Unsupported attribute
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": This value does not have any attributes.
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all":     | google_service_account.default_service_account is empty tuple
Step #1 - "tf plan validate all":     |----------------
Step #1 - "tf plan validate all":   54:   value       = google_service_account.default_service_account.name
Step #1 - "tf plan validate all":   on .terraform/modules/org_secrets/modules/core_project_factory/outputs.tf line 54, in output "service_account_name":
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": Error: Unsupported attribute
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": This value does not have any attributes.
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all":     | google_service_account.default_service_account is empty tuple
Step #1 - "tf plan validate all":     |----------------
Step #1 - "tf plan validate all":   49:   value       = google_service_account.default_service_account.email
Step #1 - "tf plan validate all":   on .terraform/modules/org_secrets/modules/core_project_factory/outputs.tf line 49, in output "service_account_email":
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": Error: Unsupported attribute
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": This value does not have any attributes.
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all":     | google_service_account.default_service_account is empty tuple
Step #1 - "tf plan validate all":     |----------------
Step #1 - "tf plan validate all":   44:   value       = google_service_account.default_service_account.display_name
Step #1 - "tf plan validate all":   on .terraform/modules/org_secrets/modules/core_project_factory/outputs.tf line 44, in output "service_account_display_name":
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": Error: Unsupported attribute
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": This value does not have any attributes.
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all":     | google_service_account.default_service_account is empty tuple
Step #1 - "tf plan validate all":     |----------------
Step #1 - "tf plan validate all":   39:   value       = google_service_account.default_service_account.account_id
Step #1 - "tf plan validate all":   on .terraform/modules/org_secrets/modules/core_project_factory/outputs.tf line 39, in output "service_account_id":
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": Error: Unsupported attribute
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": This value does not have any attributes.
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all":     | google_service_account.default_service_account is empty tuple
Step #1 - "tf plan validate all":     |----------------
Step #1 - "tf plan validate all":   39:     google_service_account.default_service_account.email,
Step #1 - "tf plan validate all":   on .terraform/modules/org_secrets/modules/core_project_factory/main.tf line 39, in locals:
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": Error: Unsupported attribute
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": This value does not have any attributes.
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all":     | google_service_account.default_service_account is empty tuple
Step #1 - "tf plan validate all":     |----------------
Step #1 - "tf plan validate all":   59:   value       = google_service_account.default_service_account.unique_id
Step #1 - "tf plan validate all":   on .terraform/modules/org_billing_logs/modules/core_project_factory/outputs.tf line 59, in output "service_account_unique_id":
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": Error: Unsupported attribute
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": This value does not have any attributes.
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all":     | google_service_account.default_service_account is empty tuple
Step #1 - "tf plan validate all":     |----------------
Step #1 - "tf plan validate all":   54:   value       = google_service_account.default_service_account.name
Step #1 - "tf plan validate all":   on .terraform/modules/org_billing_logs/modules/core_project_factory/outputs.tf line 54, in output "service_account_name":
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": Error: Unsupported attribute
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": This value does not have any attributes.
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all":     | google_service_account.default_service_account is empty tuple
Step #1 - "tf plan validate all":     |----------------
Step #1 - "tf plan validate all":   49:   value       = google_service_account.default_service_account.email
Step #1 - "tf plan validate all":   on .terraform/modules/org_billing_logs/modules/core_project_factory/outputs.tf line 49, in output "service_account_email":
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": Error: Unsupported attribute
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": This value does not have any attributes.
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all":     | google_service_account.default_service_account is empty tuple
Step #1 - "tf plan validate all":     |----------------
Step #1 - "tf plan validate all":   44:   value       = google_service_account.default_service_account.display_name
Step #1 - "tf plan validate all":   on .terraform/modules/org_billing_logs/modules/core_project_factory/outputs.tf line 44, in output "service_account_display_name":
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": Error: Unsupported attribute
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": This value does not have any attributes.
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all":     | google_service_account.default_service_account is empty tuple
Step #1 - "tf plan validate all":     |----------------
Step #1 - "tf plan validate all":   39:   value       = google_service_account.default_service_account.account_id
Step #1 - "tf plan validate all":   on .terraform/modules/org_billing_logs/modules/core_project_factory/outputs.tf line 39, in output "service_account_id":
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": Error: Unsupported attribute
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": This value does not have any attributes.
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all":     | google_service_account.default_service_account is empty tuple
Step #1 - "tf plan validate all":     |----------------
Step #1 - "tf plan validate all":   39:     google_service_account.default_service_account.email,
Step #1 - "tf plan validate all":   on .terraform/modules/org_billing_logs/modules/core_project_factory/main.tf line 39, in locals:
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": Error: Unsupported attribute
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": This value does not have any attributes.
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all":     | google_service_account.default_service_account is empty tuple
Step #1 - "tf plan validate all":     |----------------
Step #1 - "tf plan validate all":   59:   value       = google_service_account.default_service_account.unique_id
Step #1 - "tf plan validate all":   on .terraform/modules/org_audit_logs/modules/core_project_factory/outputs.tf line 59, in output "service_account_unique_id":
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": Error: Unsupported attribute
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": This value does not have any attributes.
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all":     | google_service_account.default_service_account is empty tuple
Step #1 - "tf plan validate all":     |----------------
Step #1 - "tf plan validate all":   54:   value       = google_service_account.default_service_account.name
Step #1 - "tf plan validate all":   on .terraform/modules/org_audit_logs/modules/core_project_factory/outputs.tf line 54, in output "service_account_name":
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": Error: Unsupported attribute
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": This value does not have any attributes.
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all":     | google_service_account.default_service_account is empty tuple
Step #1 - "tf plan validate all":     |----------------
Step #1 - "tf plan validate all":   49:   value       = google_service_account.default_service_account.email
Step #1 - "tf plan validate all":   on .terraform/modules/org_audit_logs/modules/core_project_factory/outputs.tf line 49, in output "service_account_email":
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": Error: Unsupported attribute
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": This value does not have any attributes.
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all":     | google_service_account.default_service_account is empty tuple
Step #1 - "tf plan validate all":     |----------------
Step #1 - "tf plan validate all":   44:   value       = google_service_account.default_service_account.display_name
Step #1 - "tf plan validate all":   on .terraform/modules/org_audit_logs/modules/core_project_factory/outputs.tf line 44, in output "service_account_display_name":
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": Error: Unsupported attribute
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": This value does not have any attributes.
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all":     | google_service_account.default_service_account is empty tuple
Step #1 - "tf plan validate all":     |----------------
Step #1 - "tf plan validate all":   39:   value       = google_service_account.default_service_account.account_id
Step #1 - "tf plan validate all":   on .terraform/modules/org_audit_logs/modules/core_project_factory/outputs.tf line 39, in output "service_account_id":
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": Error: Unsupported attribute
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": This value does not have any attributes.
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all":     | google_service_account.default_service_account is empty tuple
Step #1 - "tf plan validate all":     |----------------
Step #1 - "tf plan validate all":   39:     google_service_account.default_service_account.email,
Step #1 - "tf plan validate all":   on .terraform/modules/org_audit_logs/modules/core_project_factory/main.tf line 39, in locals:
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": Error: Unsupported attribute
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": This value does not have any attributes.
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all":     | google_service_account.default_service_account is empty tuple
Step #1 - "tf plan validate all":     |----------------
Step #1 - "tf plan validate all":   59:   value       = google_service_account.default_service_account.unique_id
Step #1 - "tf plan validate all":   on .terraform/modules/interconnect/modules/core_project_factory/outputs.tf line 59, in output "service_account_unique_id":
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": Error: Unsupported attribute
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": This value does not have any attributes.
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all":     | google_service_account.default_service_account is empty tuple
Step #1 - "tf plan validate all":     |----------------
Step #1 - "tf plan validate all":   54:   value       = google_service_account.default_service_account.name
Step #1 - "tf plan validate all":   on .terraform/modules/interconnect/modules/core_project_factory/outputs.tf line 54, in output "service_account_name":
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": Error: Unsupported attribute
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": This value does not have any attributes.
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all":     | google_service_account.default_service_account is empty tuple
Step #1 - "tf plan validate all":     |----------------
Step #1 - "tf plan validate all":   49:   value       = google_service_account.default_service_account.email
Step #1 - "tf plan validate all":   on .terraform/modules/interconnect/modules/core_project_factory/outputs.tf line 49, in output "service_account_email":
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": Error: Unsupported attribute
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": This value does not have any attributes.
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all":     | google_service_account.default_service_account is empty tuple
Step #1 - "tf plan validate all":     |----------------
Step #1 - "tf plan validate all":   44:   value       = google_service_account.default_service_account.display_name
Step #1 - "tf plan validate all":   on .terraform/modules/interconnect/modules/core_project_factory/outputs.tf line 44, in output "service_account_display_name":
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": Error: Unsupported attribute
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": This value does not have any attributes.
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all":     | google_service_account.default_service_account is empty tuple
Step #1 - "tf plan validate all":     |----------------
Step #1 - "tf plan validate all":   39:   value       = google_service_account.default_service_account.account_id
Step #1 - "tf plan validate all":   on .terraform/modules/interconnect/modules/core_project_factory/outputs.tf line 39, in output "service_account_id":
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": Error: Unsupported attribute
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": This value does not have any attributes.
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all":     | google_service_account.default_service_account is empty tuple
Step #1 - "tf plan validate all":     |----------------
Step #1 - "tf plan validate all":   39:     google_service_account.default_service_account.email,
Step #1 - "tf plan validate all":   on .terraform/modules/interconnect/modules/core_project_factory/main.tf line 39, in locals:
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": Error: Unsupported attribute
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": This value does not have any attributes.
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all":     | google_service_account.default_service_account is empty tuple
Step #1 - "tf plan validate all":     |----------------
Step #1 - "tf plan validate all":   59:   value       = google_service_account.default_service_account.unique_id
Step #1 - "tf plan validate all":   on .terraform/modules/dns_hub/modules/core_project_factory/outputs.tf line 59, in output "service_account_unique_id":
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": Error: Unsupported attribute
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": This value does not have any attributes.
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all":     | google_service_account.default_service_account is empty tuple
Step #1 - "tf plan validate all":     |----------------
Step #1 - "tf plan validate all":   54:   value       = google_service_account.default_service_account.name
Step #1 - "tf plan validate all":   on .terraform/modules/dns_hub/modules/core_project_factory/outputs.tf line 54, in output "service_account_name":
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": Error: Unsupported attribute
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": This value does not have any attributes.
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all":     | google_service_account.default_service_account is empty tuple
Step #1 - "tf plan validate all":     |----------------
Step #1 - "tf plan validate all":   49:   value       = google_service_account.default_service_account.email
Step #1 - "tf plan validate all":   on .terraform/modules/dns_hub/modules/core_project_factory/outputs.tf line 49, in output "service_account_email":
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": Error: Unsupported attribute
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": This value does not have any attributes.
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all":     | google_service_account.default_service_account is empty tuple
Step #1 - "tf plan validate all":     |----------------
Step #1 - "tf plan validate all":   44:   value       = google_service_account.default_service_account.display_name
Step #1 - "tf plan validate all":   on .terraform/modules/dns_hub/modules/core_project_factory/outputs.tf line 44, in output "service_account_display_name":
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": Error: Unsupported attribute
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": This value does not have any attributes.
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all":     | google_service_account.default_service_account is empty tuple
Step #1 - "tf plan validate all":     |----------------
Step #1 - "tf plan validate all":   39:   value       = google_service_account.default_service_account.account_id
Step #1 - "tf plan validate all":   on .terraform/modules/dns_hub/modules/core_project_factory/outputs.tf line 39, in output "service_account_id":
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": Error: Unsupported attribute
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": This value does not have any attributes.
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all":     | google_service_account.default_service_account is empty tuple
Step #1 - "tf plan validate all":     |----------------
Step #1 - "tf plan validate all":   39:     google_service_account.default_service_account.email,
Step #1 - "tf plan validate all":   on .terraform/modules/dns_hub/modules/core_project_factory/main.tf line 39, in locals:
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": Error: Unsupported attribute

**Comment by Red-Five** [comment]
@Suhasth02 
Did you set the terraform service account email in the terraform.tfvars?
The service account can be found in the cft-seed project.
E.g. 
terraform_service_account = "org-terraform@cft-seed-XXXX.iam.gserviceaccount.com"

**Comment by rjerrems** [comment]
hi @Suhasth02  - apologies for the late response. Did you end up getting past this issue?
