### ISSUE TITLE
Add organization diagram

### ISSUE THREAD

**Issue by ocervell** [terraform-google-modules/terraform-example-foundation#34]
Add an organization diagram showing what the org will roughly look like

**Comment by sbadakhc** [comment]
I think this would be really useful. How that maps to folder structure would also be really good. I would like to compare how I'm organising my folders, projects and modules with your reference architecture. I'm trying to inherit tfvars as I'm building my cloud to try and keep things DRY. I would be happy to feedback regarding this effort.

**Comment by rjerrems** [comment]
Yeah I agree this would be useful, just need to make sure to keep it up to date as the repo evolves. The text based tree hierarchy in the main README is just a stop gap until we have something better. Any body interested in contributing this?

**Comment by morgante** [comment]
FYI I actually have a preliminary tool to autogenerate org diagrams using gcpdraw we might be able to leverage: https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/536

**Comment by sbadakhc** [comment]
Thanks for feeding back gents. Much appreciated as always.

**Comment by rjerrems** [comment]
For in depth diagrams / commentary - we are now going to reference the white paper here https://services.google.com/fh/files/misc/google-cloud-security-foundations-guide.pdf
