### ISSUE TITLE
Bump bootstrap module version and expose runner image

### ISSUE THREAD

**Issue by bharathkkb** [terraform-google-modules/terraform-example-foundation#348]
With the migration of bootstrap module to GAR https://github.com/terraform-google-modules/terraform-google-bootstrap/issues/91, it is possible to use the same runner image for `app-infra-pipelines`. We should 
- upgrade bootstrap to 2.2 for 0-bootstrap
- add option to bring your own runner image (to reuse the bootstrap runner image) in 4-projects infra pipeline
- update docs

**Comment by g-awmalik** [comment]
@daniel-cit - are you still planning to work on this issue?

**Comment by bharathkkb** [comment]
Obsolete since we switched to cloudbuilder module
