### ISSUE TITLE
common.auto.tfvars link pointing to an example file

### ISSUE THREAD

**Issue by jasonbisson** [terraform-google-modules/terraform-example-foundation#350]
@bharathkkb 

Under terraform-example-foundation/4-projects/business_unit_1/shared 
the link needs to be updated to point to valid file

common.auto.tfvars -> ../common.auto.example.tfvars

**Comment by daniel-cit** [comment]
The correct soft link should be:

```
 common.auto.tfvars -> ../../common.auto.tfvars
```
like in the other links in the `4-projects` step.

The soft link in `terraform-example-foundation/4-projects/business_unit_2/shared` has the same problem.

**Comment by bharathkkb** [comment]
fixed by https://github.com/terraform-google-modules/terraform-example-foundation/pull/374
