### ISSUE TITLE
Missing backend.tf file from shared folder

### ISSUE THREAD

**Issue by jasonbisson** [terraform-google-modules/terraform-example-foundation#351]
@bharathkkb missing backend.tf file

terraform {
  backend "gcs" {
    bucket = "UPDATE_ME"
    prefix = "terraform/projects/envs/shared"
  }
}

**Comment by bharathkkb** [comment]
Also add providers with SA impersonation

**Comment by bharathkkb** [comment]
fixed by https://github.com/terraform-google-modules/terraform-example-foundation/pull/374
