### ISSUE TITLE
access_context_manager_policy_id but a value was found in file "common.auto.tfvars". 

### ISSUE THREAD

**Issue by jasonbisson** [terraform-google-modules/terraform-example-foundation#352]
@bharathkkb 

During the infra-pipeline deployment access_context_manager_policy_id is not declared.

The root module does not declare a variable named
"access_context_manager_policy_id" but a value was found in file
"common.auto.tfvars". To use this value, add a "variable" block to the
configuration.

**Comment by bharathkkb** [comment]
fixed by https://github.com/terraform-google-modules/terraform-example-foundation/pull/374
