### ISSUE TITLE
Groups required in bootstrap and SFB suggestions

### ISSUE THREAD

**Issue by aarturm** [terraform-google-modules/terraform-example-foundation#354]
Hello, 
In prerequisites for step 0-bootstrap I see "Cloud Identity / G Suite groups for organization and billing admins". I see it is in line with [Best practices for enterprise organizations](https://cloud.google.com/docs/enterprise/best-practices-for-enterprise-organizations#groups-and-service-accounts) to create such groups. 
However [Google Cloud Security Foundations Guide](https://services.google.com/fh/files/misc/google-cloud-security-foundations-guide.pdf) in chapter 6.2 states: `Note: Groups and users should not have any permissions to alter the foundation components laid out by the deployment pipeline described in Section 5 unless they are one of the privileged identities`
There are privileged identities proposed as Org Admin and Billing Admin.

Questions: 
* Is there a plan to remove prerequisites for those two admin groups in bootstrap? 
* Is there a plan to add IAM role assignment for groups (and privileged identities)  suggested in `Google Cloud Security Foundations Guide`?

**Comment by rjerrems** [comment]
Hi @aarturm - great questions.

>Is there a plan to remove prerequisites for those two admin groups in bootstrap?

For the org admins group, I think we need to provide clearer guidance on when/how it is used. Two patterns I am aware of are:

1. After you have successfully built the foundation, remove the user/s from the org admins group and only use for break glass purposes. (it allows you to impersonate the terraform service account for tricky terraform issues that might require you to debug interactively)

2. The user/s that are in this group are highly privileged break glass users, which have stringent controls on when and how they are used. (again you may enforce these controls after the foundation is built)

For the billing admin group, I would anticipate that you would still have users in this group as they are required for comms relating to billing issues and to administer the billing account. (as well as having access to billing data, once you have setup the export to BigQuery which is setup on the 1-org here https://github.com/terraform-google-modules/terraform-example-foundation/blob/master/1-org/envs/shared/log_sinks.tf#L121)

> Is there a plan to add IAM role assignment for groups (and privileged identities) suggested in Google Cloud Security Foundations Guide?

I think it would make sense for us to add this at some point in the future.

**Comment by bharathkkb** [comment]
fixed by #446
