### ISSUE TITLE
4-Projects Module Terraform Version Conflict

### ISSUE THREAD

**Issue by mchloud** [terraform-google-modules/terraform-example-foundation#357]
Hello,

In deploying the example foundation per what appears to be the advised version of 12.20, and running Terraform locally, all appears well until beginning the first step of the 4-Projects modules instantiation. 

On running locally:
./tf-wrapper.sh init production

An error is thrown: 
*************** TERRAFORM INIT *******************
      At environment: business_unit_1/production
**************************************************
Initializing modules...
There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.

Error: Unsupported block type

  on .terraform/modules/peering/modules/network-peering/versions.tf line 26, in terraform:
  26:   provider_meta "google" {

Blocks of type "provider_meta" are not expected here.

Tracking the called module itself appears to indicate that as of Dec 2020 the TF version constraint was increased to 13, however as noted in discussions here (and through attempting to deploy myself) it appears that the Example Foundation is not ready to support version 13 at large. 

Any input as to remediation would be appreciated.

**Comment by bharathkkb** [comment]
Hi @mchloud 
A quick workaround for this is to pin [that module ](https://github.com/terraform-google-modules/terraform-example-foundation/blob/f87ed1661bec7c2d2c75ea091d1cf5db6ac6943a/4-projects/business_unit_1/development/example_peering_project.tf#L68) to last supported 0.12.x release. 
```
version = "~> 2.0"
```
We have a fix https://github.com/terraform-google-modules/terraform-example-foundation/pull/333 but have not merged yet. Feel free to reopen if needed.
