### ISSUE TITLE
Define and source common variables on from location.

### ISSUE THREAD

**Issue by sbadakhc** [terraform-google-modules/terraform-example-foundation#36]
Hi,

Can the terraform.tfvars in the different step folders source common values from the previous step? If the intention is to run these steps in sequence shouldn't we be defining in values in one place? Either method is better than duplicating the values. Best to keep things DRY.

Thanks,
Sal.

**Comment by rjerrems** [comment]
Hi @sbadakhc - Thanks for the feedback. Part of the reason we have separate terraform files is that each of the steps from 1 onwards are designed to be run independently as separate pipelines in cloud build (with separate repos). If you do end up using Cloud Build, we have substitutions which are available from the bootstrap module to minimize repetition although we have not yet had the chance to include these in the example cloud build yaml files:

https://github.com/terraform-google-modules/terraform-google-bootstrap/blob/master/modules/cloudbuild/main.tf#L177

If you do plan to keep things in a single repo or are not planning to use Cloud Build, this blog post gives some detail on how you might be able to make the code more DRY as you have mentioned

https://medium.com/datamindedbe/running-through-the-google-gcp-cloud-foundation-toolkit-setup-b4c5a912da56

**Comment by morgante** [comment]
One approach I've taken for this before is creating a common `info` module. You fill in common customizations there (on your fork) and every other environment/module sources from there.

**Comment by sbadakhc** [comment]
Thanks for the info. I'll take a look and feedback.
