### ISSUE TITLE
Bucket for tf-state created with wrong prefix

### ISSUE THREAD

**Issue by amandakarina** [terraform-google-modules/terraform-example-foundation#363]
The bucket created on step 0-bootstrap to save the terraform state is being created with prefix prj instead of bkt.

**Comment by bharathkkb** [comment]
I believe this is expected behavior on bootstrap. We should override in example-foundation via `state_bucket_name`

**Comment by rjerrems** [comment]
Fixed by https://github.com/terraform-google-modules/terraform-example-foundation/pull/407
