### ISSUE TITLE
[DEVELOP] Cloud build YAML templates need to be updated to use Google Artifact Registry

### ISSUE THREAD

**Issue by daniel-cit** [terraform-google-modules/terraform-example-foundation#366]
Bootstrap sub module [cloudbuild](https://github.com/terraform-google-modules/terraform-google-bootstrap/tree/master/modules/cloudbuild) now uses [Artifact registry](https://cloud.google.com/artifact-registry/docs/transition/transition-from-gcr) instead of Container Registry since version [v2.2.0](https://github.com/terraform-google-modules/terraform-google-bootstrap/releases/tag/v2.2.0).

On a **fresh** deploy from the `develop` branch on a newly created cloud build project cloud build fails with:

```
Starting Step #0 - "setup"
Step #0 - "setup": Pulling image: gcr.io/prj-cloudbuild-34b9/terraform
Step #0 - "setup": Using default tag: latest
Step #0 - "setup": Error response from daemon: manifest for gcr.io/prj-cloudbuild-34b9/terraform:latest not found: manifest unknown: Failed to fetch "latest" from request "/v2/prj-cloudbuild-34b9/terraform/manifests/latest".
```

Cloud build files:

- [cloudbuild-tf-apply.yaml](https://github.com/terraform-google-modules/terraform-example-foundation/blob/develop/build/cloudbuild-tf-apply.yaml)
- [cloudbuild-tf-plan.yaml](https://github.com/terraform-google-modules/terraform-example-foundation/blob/develop/build/cloudbuild-tf-plan.yaml)

need to be updated to use the Artifact Registry, changing the location of the runner images from:

```
gcr.io/$PROJECT_ID/terraform
```

to:

```
$_DEFAULT_REGION-docker.pkg.dev/$PROJECT_ID/prj-tf-runners/terraform
```

**Comment by bharathkkb** [comment]
Thanks @daniel-cit I have exposed `_GAR_REPOSITORY` https://github.com/terraform-google-modules/terraform-google-bootstrap/pull/98 to use in the yamls. I'll cut a release to unblock.

**Comment by daniel-cit** [comment]
Fixed by https://github.com/terraform-google-modules/terraform-example-foundation/pull/367
