### ISSUE TITLE
[DEVELOP] Hub and Spoke configuration in usage README.md

### ISSUE THREAD

**Issue by renato-rudnicki** [terraform-google-modules/terraform-example-foundation#369]
Can we have an example for [Hub and Spoke](https://cloud.google.com/managed-microsoft-ad/docs/hub-spoke) configuration in the usage section in README.md for 1-org and 3-networks ?

**Comment by caleonardo** [comment]
@drebes and @averbuks - Are you able to help on this?

**Comment by drebes** [comment]
Hi, can you point us to examples on the same lines of what you need us to do? Thanks.
