### ISSUE TITLE
Reduce params within network envs and create common baseline env

### ISSUE THREAD

**Issue by bharathkkb** [terraform-google-modules/terraform-example-foundation#392]
Current we [parameterize](https://github.com/terraform-google-modules/terraform-example-foundation/blob/develop/3-networks/envs/development/main.tf#L108-L121) most values from `base_shared_vpc ` `restricted_shared_vpc` modules. We should reduce this and default to module variable defaults with instructions to modify the env directly if needed

**Comment by morgante** [comment]
We also shouldn't have so many top-level modules in the environments. The intention is that the environment folder just invokes an environment module, instead of composing multiple modules in the environment folder.
