### ISSUE TITLE
Remove optional firewall rules from network modules

### ISSUE THREAD

**Issue by rjerrems** [terraform-google-modules/terraform-example-foundation#408]
Now that these are implemented in hierarchical firewall, we should remove them from the network modules

https://github.com/terraform-google-modules/terraform-example-foundation/blob/master/3-networks/modules/base_shared_vpc/firewall.tf#L74

https://github.com/terraform-google-modules/terraform-example-foundation/blob/master/3-networks/modules/restricted_shared_vpc/firewall.tf#L73

**Comment by caleonardo** [comment]
@juliocc FYI
