### ISSUE TITLE
terraform-validator fails when adding organization policy to a project

### ISSUE THREAD

**Issue by vovinacci** [terraform-google-modules/terraform-example-foundation#418]
Hi,

  When adding organization policy constraint for a project in `3-networks`, `terraform-validator` fails with 

```
Error: validating: FCV: converting asset //cloudresourcemanager.googleapis.com/projects/prj-p-some-project-1234 to proto: unmarshaling to proto: json: cannot unmarshal object into Go value of type string
```

How to reproduce:

- Create project with no custom policies
- Add org policy to the project

```
// Allow VMs with external IP addresses in this project
module "org_vm_external_ip_access" {
  source      = "terraform-google-modules/org-policy/google"
  version     = "~> 3.0"
  project_id  = local.base_project_id
  policy_for  = "project"
  policy_type = "list"
  enforce     = "false"
  constraint  = "constraints/compute.vmExternalIpAccess"
}
```

Did you experience this before?
Many thanks in advance.

**Comment by vovinacci** [comment]
@daniel-cit I can see that this been fixed in upstream. How do we want to proceed?

**Comment by daniel-cit** [comment]
Hi @vovinacci, I tested a version with the fix and we need another issue to be fixed before updating the terraform-validator version: https://github.com/GoogleCloudPlatform/terraform-validator/issues/216

**Comment by vovinacci** [comment]
Thanks much for the update!

**Comment by melinath** [comment]
The Terraform Validator fix has been merged.

**Comment by vovinacci** [comment]
@melinath Many thanks for the update, will test it this evening and get back to you.

**Comment by bharathkkb** [comment]
Thanks @melinath @vovinacci 
Happy to review a PR to bump the tfv version we use as well.

**Comment by vovinacci** [comment]
@bharathkkb Will create one.

**Comment by vovinacci** [comment]
@melinath Works like a charm, thank you very much.
