### ISSUE TITLE
1-org scc notifications create - 500 Internal error occurred

### ISSUE THREAD

**Issue by matt-declarativecloud** [terraform-google-modules/terraform-example-foundation#453]
## Using Cloud Build

Step 18  Terraform Apply fails with

`ERROR: (gcloud.scc.notifications.create) HttpError accessing <https://securitycenter.googleapis.com/v1/organizations/492892508434/notificationConfigs?alt=json&configId=NOTIFICATION_NAME>: response: <{'vary': 'Origin, X-Origin, Referer', 'content-type': 'application/json; charset=UTF-8', 'content-encoding': 'gzip', 'date': 'Sun, 25 Apr 2021 22:43:40 GMT', 'server': 'ESF', 'cache-control': 'private', 'x-xss-protection': '0', 'x-frame-options': 'SAMEORIGIN', 'x-content-type-options': 'nosniff', 'transfer-encoding': 'chunked', 'status': 500}>, content <{
  "error": {
    "code": 500,
    "message": "Internal error encountered.",
    "status": "INTERNAL"
  }
}`

## Workaround

No programmatic workaround yet

1. In Security Command Center follow the _Get Started_ steps to provision an organization-level Service Account 
2. Choose _Grant Required Roles_  or copy and run the `gcloud` commands shown to grant the Security Command Center Service Account necessary permissions

## Debug
===================================

`gcloud alpha scc notifications create NOTIFICATION_NAME     --organization "492892508434"     --description "SCC Notification for all active findings"     --pubsub-topic "projects/prj-c-scc-75d9/topics/top-scc-notification"     --filter "state=\"ACTIVE\""     --project "prj-c-scc-75d9"     --impersonate-service-account=org-terraform@prj-b-seed-212c.iam.gserviceaccount.com --verbosity debug`

DEBUG: Starting new HTTPS connection (1): iamcredentials.googleapis.com:443
DEBUG: https://iamcredentials.googleapis.com:443 "POST /v1/projects/-/serviceAccounts/org-terraform@prj-b-seed-212c.iam.gserviceaccount.com:generateAccessToken HTTP/1.1" 200 None
DEBUG: Starting new HTTPS connection (1): securitycenter.googleapis.com:443
DEBUG: https://securitycenter.googleapis.com:443 "POST /v1/organizations/492892508434/notificationConfigs?alt=json&configId=NOTIFICATION_NAME HTTP/1.1" 500 None
DEBUG: Response returned status 500, retrying
DEBUG: Retrying request to url https://securitycenter.googleapis.com/v1/organizations/492892508434/notificationConfigs?alt=json&configId=NOTIFICATION_NAME after exception HttpError accessing <https://securitycenter.googleapis.com/v1/organizations/492892508434/notificationConfigs?alt=json&configId=NOTIFICATION_NAME>: response: <{'vary': 'Origin, X-Origin, Referer', 'content-type': 'application/json; charset=UTF-8', 'content-encoding': 'gzip', 'date': 'Sun, 25 Apr 2021 22:43:09 GMT', 'server': 'ESF', 'cache-control': 'private', 'x-xss-protection': '0', 'x-frame-options': 'SAMEORIGIN', 'x-content-type-options': 'nosniff', 'transfer-encoding': 'chunked', 'status': 500}>, content <{
  "error": {
    "code": 500,
    "message": "Internal error encountered.",
    "status": "INTERNAL"
  }
}
>
DEBUG: https://securitycenter.googleapis.com:443 "POST /v1/organizations/492892508434/notificationConfigs?alt=json&configId=NOTIFICATION_NAME HTTP/1.1" 500 None
DEBUG: Response returned status 500, retrying
DEBUG: Retrying request to url https://securitycenter.googleapis.com/v1/organizations/492892508434/notificationConfigs?alt=json&configId=NOTIFICATION_NAME after exception HttpError accessing <https://securitycenter.googleapis.com/v1/organizations/492892508434/notificationConfigs?alt=json&configId=NOTIFICATION_NAME>: response: <{'vary': 'Origin, X-Origin, Referer', 'content-type': 'application/json; charset=UTF-8', 'content-encoding': 'gzip', 'date': 'Sun, 25 Apr 2021 22:43:12 GMT', 'server': 'ESF', 'cache-control': 'private', 'x-xss-protection': '0', 'x-frame-options': 'SAMEORIGIN', 'x-content-type-options': 'nosniff', 'transfer-encoding': 'chunked', 'status': 500}>, content <{
  "error": {
    "code": 500,
    "message": "Internal error encountered.",
    "status": "INTERNAL"
  }
}
>
DEBUG: Starting new HTTPS connection (1): securitycenter.googleapis.com:443
DEBUG: https://securitycenter.googleapis.com:443 "POST /v1/organizations/492892508434/notificationConfigs?alt=json&configId=NOTIFICATION_NAME HTTP/1.1" 500 None
DEBUG: Response returned status 500, retrying
DEBUG: Retrying request to url https://securitycenter.googleapis.com/v1/organizations/492892508434/notificationConfigs?alt=json&configId=NOTIFICATION_NAME after exception HttpError accessing <https://securitycenter.googleapis.com/v1/organizations/492892508434/notificationConfigs?alt=json&configId=NOTIFICATION_NAME>: response: <{'vary': 'Origin, X-Origin, Referer', 'content-type': 'application/json; charset=UTF-8', 'content-encoding': 'gzip', 'date': 'Sun, 25 Apr 2021 22:43:09 GMT', 'server': 'ESF', 'cache-control': 'private', 'x-xss-protection': '0', 'x-frame-options': 'SAMEORIGIN', 'x-content-type-options': 'nosniff', 'transfer-encoding': 'chunked', 'status': 500}>, content <{
  "error": {
    "code": 500,
    "message": "Internal error encountered.",
    "status": "INTERNAL"
  }
}
>
DEBUG: https://securitycenter.googleapis.com:443 "POST /v1/organizations/492892508434/notificationConfigs?alt=json&configId=NOTIFICATION_NAME HTTP/1.1" 500 None
DEBUG: Response returned status 500, retrying
DEBUG: Retrying request to url https://securitycenter.googleapis.com/v1/organizations/492892508434/notificationConfigs?alt=json&configId=NOTIFICATION_NAME after exception HttpError accessing <https://securitycenter.googleapis.com/v1/organizations/492892508434/notificationConfigs?alt=json&configId=NOTIFICATION_NAME>: response: <{'vary': 'Origin, X-Origin, Referer', 'content-type': 'application/json; charset=UTF-8', 'content-encoding': 'gzip', 'date': 'Sun, 25 Apr 2021 22:43:12 GMT', 'server': 'ESF', 'cache-control': 'private', 'x-xss-protection': '0', 'x-frame-options': 'SAMEORIGIN', 'x-content-type-options': 'nosniff', 'transfer-encoding': 'chunked', 'status': 500}>, content <{
  "error": {
    "code": 500,
    "message": "Internal error encountered.",
    "status": "INTERNAL"
  }
}
>
DEBUG: https://securitycenter.googleapis.com:443 "POST /v1/organizations/492892508434/notificationConfigs?alt=json&configId=NOTIFICATION_NAME HTTP/1.1" 500 None
DEBUG: Response returned status 500, retrying
DEBUG: Retrying request to url https://securitycenter.googleapis.com/v1/organizations/492892508434/notificationConfigs?alt=json&configId=NOTIFICATION_NAME after exception HttpError accessing <https://securitycenter.googleapis.com/v1/organizations/492892508434/notificationConfigs?alt=json&configId=NOTIFICATION_NAME>: response: <{'vary': 'Origin, X-Origin, Referer', 'content-type': 'application/json; charset=UTF-8', 'content-encoding': 'gzip', 'date': 'Sun, 25 Apr 2021 22:43:16 GMT', 'server': 'ESF', 'cache-control': 'private', 'x-xss-protection': '0', 'x-frame-options': 'SAMEORIGIN', 'x-content-type-options': 'nosniff', 'transfer-encoding': 'chunked', 'status': 500}>, content <{
  "error": {
    "code": 500,
    "message": "Internal error encountered.",
    "status": "INTERNAL"
  }
}
This may be due to network connectivity issues. Please check your network settings, and the status of the service you are trying to reach.
Traceback (most recent call last):
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 982, in Execute
    resources = calliope_command.Run(cli=self, args=args)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 809, in Run
    resources = command_instance.Run(args)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/command_lib/util/apis/yaml_command_translator.py", line 305, in Run
    ref, response = self._CommonRun(args)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/command_lib/util/apis/yaml_command_translator.py", line 953, in _CommonRun
    page_size=self.arg_generator.PageSize(args))
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/command_lib/util/apis/registry.py", line 334, in Call
    return request_func(global_params=global_params)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/command_lib/util/apis/registry.py", line 393, in RequestFunc
    return method(request, global_params=global_params)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/third_party/apis/securitycenter/v1/securitycenter_v1_client.py", line 479, in Create
    config, request, global_params=global_params)
  File "/usr/bin/../lib/google-cloud-sdk/lib/third_party/apitools/base/py/base_api.py", line 729, in _RunMethod
    http, http_request, **opts)
  File "/usr/bin/../lib/google-cloud-sdk/lib/third_party/apitools/base/py/http_wrapper.py", line 350, in MakeRequest
    check_response_func=check_response_func)
  File "/usr/bin/../lib/google-cloud-sdk/lib/third_party/apitools/base/py/http_wrapper.py", line 406, in _MakeRequestNoRetry
    check_response_func(response)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/api_lib/util/apis.py", line 267, in _CheckResponseForApiEnablement
    http_wrapper.CheckResponse(response)
  File "/usr/bin/../lib/google-cloud-sdk/lib/third_party/apitools/base/py/http_wrapper.py", line 223, in CheckResponse
    raise exceptions.BadStatusCodeError.FromResponse(response)
apitools.base.py.exceptions.BadStatusCodeError: HttpError accessing <https://securitycenter.googleapis.com/v1/organizations/492892508434/notificationConfigs?alt=json&configId=NOTIFICATION_NAME>: response: <{'vary': 'Origin, X-Origin, Referer', 'content-type': 'application/json; charset=UTF-8', 'content-encoding': 'gzip', 'date': 'Sun, 25 Apr 2021 22:43:40 GMT', 'server': 'ESF', 'cache-control': 'private', 'x-xss-protection': '0', 'x-frame-options': 'SAMEORIGIN', 'x-content-type-options': 'nosniff', 'transfer-encoding': 'chunked', 'status': 500}>, content <{
  "error": {
    "code": 500,
    "message": "Internal error encountered.",
    "status": "INTERNAL"
  }
}
>
ERROR: (gcloud.scc.notifications.create) HttpError accessing <https://securitycenter.googleapis.com/v1/organizations/492892508434/notificationConfigs?alt=json&configId=NOTIFICATION_NAME>: response: <{'vary': 'Origin, X-Origin, Referer', 'content-type': 'application/json; charset=UTF-8', 'content-encoding': 'gzip', 'date': 'Sun, 25 Apr 2021 22:43:40 GMT', 'server': 'ESF', 'cache-control': 'private', 'x-xss-protection': '0', 'x-frame-options': 'SAMEORIGIN', 'x-content-type-options': 'nosniff', 'transfer-encoding': 'chunked', 'status': 500}>, content <{
  "error": {
    "code": 500,
    "message": "Internal error encountered.",
    "status": "INTERNAL"
  }
}
>
This may be due to network connectivity issues. Please check your network settings, and the status of the service you are trying to reach.

**Comment by rjerrems** [comment]
Fixed by https://github.com/terraform-google-modules/terraform-example-foundation/pull/467
