### ISSUE TITLE
Don't run full integration tests if only docs have been updated.

### ISSUE THREAD

**Issue by rjerrems** [terraform-google-modules/terraform-example-foundation#468]
Given how many resources get created in integration tests & possibility of naming collisions for projects we should try to avoid running integration tests when we know only documentation has been updated.

**Comment by bharathkkb** [comment]
@rjerrems Did some digging and I think we maybe able to leverage [ignored_files](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloudbuild_trigger#ignored_files) on markdown for this. Possibly good to rollout throughout our repos integration tests, once I validate if this works.

/cc @morgante if you have any thoughts

**Comment by morgante** [comment]
Yes I think leveraging ignored_files is a good idea.

**Comment by rjerrems** [comment]
Awesome, thanks for looking into that! I think it will be good for the many
repos that create projects, although on a small subset of PRs only touch
docs.

**Comment by bharathkkb** [comment]
fixed via https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/913
