### ISSUE TITLE
Question: business unit folders

### ISSUE THREAD

**Issue by matt-declarativecloud** [terraform-google-modules/terraform-example-foundation#474]
Looking for guidance using business unit folders as discussed in [#131](https://github.com/terraform-google-modules/terraform-example-foundation/pull/131).

I understand the security foundations guide example.com reference architecture uses a single layer of folders, but I have a request to add an additional folder level within environments for grouping projects. Any direction would be greatly appreciated.

**Comment by rjerrems** [comment]
My suggestion would be to look at adding these additional folders in the environments module here (assuming you want consistent folders across environments).

https://github.com/terraform-google-modules/terraform-example-foundation/tree/master/2-environments/modules/env_baseline

You would then need to add some update the data lookup here for each environment/business unit to get the new folder:

https://github.com/terraform-google-modules/terraform-example-foundation/blob/master/4-projects/business_unit_1/production/folder.tf#L17

which should allow you to create something like 

```
.
└── fldr-production
    ├── business_unit_1
    │   └── project
    ├── business_unit_2
    │   └── project
    └── business_unit_3
        └── project
```

Does that help for what you are looking for?

**Comment by matt-declarativecloud** [comment]
Thank you for the help @rjerrems have it working [here](https://github.com/matt-declarativecloud/terraform-example-foundation/commit/fdcb150581d04b432c0e4e82fa7c4d434d5ff43c)
