### ISSUE TITLE
tf-wrapper.sh permission denied in cloudbuild-tf-plan.yaml and cloudbuild-tf-apply.yaml

### ISSUE THREAD

**Issue by cjtireus** [terraform-google-modules/terraform-example-foundation#477]
when running a Cloud Build deployment using  cloudbuild-tf-plan.yaml or cloudbuild-tf-apply.yaml I get a permission denied on the tf-wrapper.sh. I guess the container don't allow me to execute the script file. Not sure if it's only for me but adding adding a step in the yaml files helped.

# [START allow tf-wrapper exec]
- id: 'allow tf-wrapper exec'
  name: $_DEFAULT_REGION-docker.pkg.dev/$PROJECT_ID/$_GAR_REPOSITORY/terraform
  entrypoint: /bin/bash
  args:
  - -c
  - |
     chmod 755 ./tf-wrapper.sh

 More people having this issue? Maybe a PR to add this?

**Comment by bharathkkb** [comment]
Thanks for the report @cjtireus 
@daniel-cit @renato-rudnicki have you seen this during testing within CB? I did a quick check and https://github.com/terraform-google-modules/terraform-example-foundation/blob/master/build/tf-wrapper.sh seems to have executable permissions.

**Comment by renato-rudnicki** [comment]
@bharathkkb I didn't face any issues related to permission denied on tf-wrapper.sh. Also, yesterday I deployed the latest version of foundation and everything ran smooth.
