### ISSUE TITLE
 ./tf-wrapper.sh apply production fails with some 409 alreadyExists errors

### ISSUE THREAD

**Issue by cjtireus** [terraform-google-modules/terraform-example-foundation#478]
the cloudbuild-tf-apply.yaml fails in Cloud Build. All other steps are OK but step 5 (apply) generates these errors. 

Step #5 - "tf apply": Error: googleapi: Error 409: Sink sk-c-logging-bq already exists, alreadyExists
Step #5 - "tf apply": 
Step #5 - "tf apply":   on .terraform/modules/log_export_to_biqquery/main.tf line 73, in resource "google_logging_organization_sink" "sink":
Step #5 - "tf apply":   73: resource "google_logging_organization_sink" "sink" {
Step #5 - "tf apply": 
Step #5 - "tf apply": 
Step #5 - "tf apply": 
Step #5 - "tf apply": Error: googleapi: Error 409: Sink sk-c-logging-pub already exists, alreadyExists
Step #5 - "tf apply": 
Step #5 - "tf apply":   on .terraform/modules/log_export_to_pubsub/main.tf line 73, in resource "google_logging_organization_sink" "sink":
Step #5 - "tf apply":   73: resource "google_logging_organization_sink" "sink" {
Step #5 - "tf apply": 
Step #5 - "tf apply": 
Step #5 - "tf apply": 
Step #5 - "tf apply": Error: googleapi: Error 409: Sink sk-c-logging-bkt already exists, alreadyExists
Step #5 - "tf apply": 
Step #5 - "tf apply":   on .terraform/modules/log_export_to_storage/main.tf line 73, in resource "google_logging_organization_sink" "sink":
Step #5 - "tf apply":   73: resource "google_logging_organization_sink" "sink" {
Step #5 - "tf apply": 
Step #5 - "tf apply": 

Anyone seen these before? Resolutions?

**Comment by cjtireus** [comment]
Looks like these sinks are created at the org level and if anything fails, these needs to be manually removed. Terraform don't handle creating and re-creating these very well. But if you run into the problem above, just remove these sinks manually and then recreate using Cloud Build. 

To remove,

gcloud logging sinks list --limit=10 --organization XXXXXXXX

gcloud logging sinks delete sk-c-logging-bq --organization XXXXXXXX
gcloud logging sinks delete sk-c-logging-bkt  --organization XXXXXXXX
gcloud logging sinks delete sk-c-logging-pub  --organization XXXXXXXX

gcloud logging sinks list --limit=10 --organization XXXXXXXX

**Comment by bharathkkb** [comment]
Hi @cjtireus 
Thanks for the report. Was all the TF run via the pipeline, I am wondering what created these sinks in the first place?
