### ISSUE TITLE
[UX] Pushing to empty repos created in CSR with init.defaultBranch set

### ISSUE THREAD

**Issue by bharathkkb** [terraform-google-modules/terraform-example-foundation#486]
Following [1-org instructions step 5](https://github.com/terraform-google-modules/terraform-example-foundation/tree/master/1-org#deploying-with-cloud-build), after cloning an empty CSR repo and making the first commit push `git push --set-upstream origin master` may return `error: src refspec master does not match any`. This could be due to `init.defaultBranch` being set to something other than master (`main` for instance)

We should update docs to make users aware of this and switch our defaults to explicitly be main `git push --set-upstream origin main`. I don't anticipate any other code changes as we name our real main branches same as envs.

**Comment by bharathkkb** [comment]
Also worth noting is the `warning: You appear to have cloned an empty repository.` warning. We should let users know this is expected.

**Comment by mark1000** [comment]
Change to master->main everywhere

**Comment by mark1000** [comment]
to determine default branch:
git config init.defaultBranch
should print back "main"

To set default branch:
git config --global init.defaultBranch main

**Comment by bharathkkb** [comment]
Fixed via https://github.com/terraform-google-modules/terraform-example-foundation/pull/538
Remaining work of updating script tracked in https://github.com/terraform-google-modules/terraform-example-foundation/issues/552
