### ISSUE TITLE
[UX] Indicate what TF command will run for push to a given branch

### ISSUE THREAD

**Issue by bharathkkb** [terraform-google-modules/terraform-example-foundation#487]
Alongside [existing steps](https://github.com/terraform-google-modules/terraform-example-foundation/tree/master/2-environments#:~:text=push%20your%20plan%20branch%20to%20trigger%20a%20plan%20for%20all%20environments) for git push to a branch, we should also document what Terraform command will be run by the CI. This will

- cement the idea of what commands are applied to main vs non main branches 
- allow users who are unfamiliar with TF to understand if it failed/passed during plan or apply

**Comment by mark1000** [comment]
https://github.com/terraform-google-modules/terraform-example-foundation/blob/997e7c8dcc6e5d3107814e0ab97b91bd2ed27506/0-bootstrap/main.tf#L149
Git push to any of these produces an apply
Git push to any others results in plan being run

**Comment by mark1000** [comment]
If pushing to these branches
terraform_apply_branches = [
    "development",
    "non\\-production", //non-production needs a \ to ensure regex matches correct branches.
    "production"
  ]
then everything including "apply" is run. terraform init, plan, validate, apply
For every other branch (non-named branches), apply is not run.
Add to FAQ: what terraform commands are run for each branch
Cross link from where we talk about pushing to named branch (aka plan branch).

**Comment by mark1000** [comment]
Bharath: Can you take a look at
https://github.com/mark1000/terraform-example-foundation/blob/487/docs/FAQ.md
and
https://github.com/mark1000/terraform-example-foundation/blob/487/2-environments/README.md
to see if this is what you're looking for? If so, I'll make the changes to other READMEs.

**Comment by bharathkkb** [comment]
@mark1000 that LGTM

**Comment by bharathkkb** [comment]
fixed via https://github.com/terraform-google-modules/terraform-example-foundation/pull/553
