### ISSUE TITLE
[UX] Mention where to clone repos to

### ISSUE THREAD

**Issue by bharathkkb** [terraform-google-modules/terraform-example-foundation#489]
Currently we have instructions to just [clone repo](https://github.com/terraform-google-modules/terraform-example-foundation/tree/master/2-environments#:~:text=clone%20repo.).  We should mention 

- which dir the user is expected to be if they want the subsequent copy commands to work as is
- note that this is not a hard requirement and they can clone to any place on their local machine as long as they adjust their copy commands

**Comment by mark1000** [comment]
Which directory should we tell them to be in? Do we say something like
The following commands assume you are in the gcp-environments directory. If you run the commands from another directory, adjust paths accordingly.
...or, something else?

**Comment by mark1000** [comment]
git clone creates the example-foundations
Run the rest of the commands from the parent directory for example-foundations

**Comment by mark1000** [comment]
rootDir
  \ example-foundation
   \ 1-org-repo
    \ 2-ens-repo

**Comment by mark1000** [comment]
Created pull request. Hoping it's what we needed.
Not sure how to tag this bug in the pull request except by manually mentioning it. Is there something else I should do?
