### ISSUE TITLE
Hub and spoke - no vpn.tf.example in 3-networks/envs/shared/

### ISSUE THREAD

**Issue by matt-declarativecloud** [terraform-google-modules/terraform-example-foundation#493]
Testing VPN with hub and spoke and noticed there's no `vpn.tf.example` in `3-networks/envs/shared/` like there is for `interconnect.tf.example` and `partner_interconnect.tf.example`.

**Comment by bharathkkb** [comment]
Thanks for the report @matt-declarativecloud
I had an original issue open fo this that got aged out https://github.com/terraform-google-modules/terraform-example-foundation/issues/310. Closing this in favor of the original issue.
Happy to review a PR as well.
