### ISSUE TITLE
error creating project prj-c-dns-hub-c98c (prj-c-dns-hub): googleapi: Error 409: Requested entity already exists, alreadyExists.

### ISSUE THREAD

**Issue by akorzynski** [terraform-google-modules/terraform-example-foundation#494]
Hello! 

I'm creating the infrastructure using the instructions in the terraform-example-foundation repo. The process failed due to project and billing quotas, as predicted in the Troubleshooting file in the repo: 
[Project quota exceeded](https://github.com/terraform-google-modules/terraform-example-foundation/blob/master/docs/TROUBLESHOOTING.md#project-quota-exceeded)
[Billing quota exceeded](https://github.com/terraform-google-modules/terraform-example-foundation/blob/master/docs/TROUBLESHOOTING.md#Billing-quota-exceeded)
After requesting Google to increase the quotas, Terraform fails complaining that the projects already exist:

Step #4 - "tf apply": Error: error creating project prj-c-dns-hub-c98c (prj-c-dns-hub): googleapi: Error 409: Requested entity already exists, alreadyExists. If you received a 403 error, make sure you have the `roles/resourcemanager.projectCreator` permission
Step #4 - "tf apply": 
Step #4 - "tf apply":   on .terraform/modules/dns_hub/modules/core_project_factory/main.tf line 65, in resource "google_project" "main":
Step #4 - "tf apply":   65: resource "google_project" "main" {
Step #4 - "tf apply": 
Step #4 - "tf apply": 
Step #4 - "tf apply": 
Step #4 - "tf apply": Error: error creating project prj-c-interconnect-8fd0 (prj-c-interconnect): googleapi: Error 409: Requested entity already exists, alreadyExists. If you received a 403 error, make sure you have the `roles/resourcemanager.projectCreator` permission
Step #4 - "tf apply": 
Step #4 - "tf apply":   on .terraform/modules/interconnect/modules/core_project_factory/main.tf line 65, in resource "google_project" "main":
Step #4 - "tf apply":   65: resource "google_project" "main" {
Step #4 - "tf apply": 
Step #4 - "tf apply": 
Step #4 - "tf apply": 
Step #4 - "tf apply": Error: error creating project prj-c-logging-9a94 (prj-c-logging): googleapi: Error 409: Requested entity already exists, alreadyExists. If you received a 403 error, make sure you have the `roles/resourcemanager.projectCreator` permission
Step #4 - "tf apply": 
Step #4 - "tf apply":   on .terraform/modules/org_audit_logs/modules/core_project_factory/main.tf line 65, in resource "google_project" "main":
Step #4 - "tf apply":   65: resource "google_project" "main" {
Step #4 - "tf apply": 
Step #4 - "tf apply": 
Step #4 - "tf apply": 
Step #4 - "tf apply": Error: error creating project prj-c-billing-logs-688a (prj-c-billing-logs): googleapi: Error 409: Requested entity already exists, alreadyExists. If you received a 403 error, make sure you have the `roles/resourcemanager.projectCreator` permission
Step #4 - "tf apply": 
Step #4 - "tf apply":   on .terraform/modules/org_billing_logs/modules/core_project_factory/main.tf line 65, in resource "google_project" "main":
Step #4 - "tf apply":   65: resource "google_project" "main" {
Step #4 - "tf apply": 
Step #4 - "tf apply": 
Step #4 - "tf apply": 
Step #4 - "tf apply": Error: error creating project prj-c-secrets-22d0 (prj-c-secrets): googleapi: Error 409: Requested entity already exists, alreadyExists. If you received a 403 error, make sure you have the `roles/resourcemanager.projectCreator` permission
Step #4 - "tf apply": 
Step #4 - "tf apply":   on .terraform/modules/org_secrets/modules/core_project_factory/main.tf line 65, in resource "google_project" "main":
Step #4 - "tf apply":   65: resource "google_project" "main" {
Step #4 - "tf apply": 
Step #4 - "tf apply": 
Step #4 - "tf apply": 
Step #4 - "tf apply": Error: error creating project prj-c-scc-1816 (prj-c-scc): googleapi: Error 409: Requested entity already exists, alreadyExists. If you received a 403 error, make sure you have the `roles/resourcemanager.projectCreator` permission
Step #4 - "tf apply": 
Step #4 - "tf apply":   on .terraform/modules/scc_notifications/modules/core_project_factory/main.tf line 65, in resource "google_project" "main":
Step #4 - "tf apply":   65: resource "google_project" "main" {
Step #4 - "tf apply": 
Step #4 - "tf apply": 
Finished Step #4 - "tf apply"
ERROR
ERROR: build step 4 "us-central1-docker.pkg.dev/prj-b-cicd-797e/prj-tf-runners/terraform" failed: step exited with non-zero status: 1

**Comment by bharathkkb** [comment]
Hi @akorzynski 
This is possibly because the project was created but billing was not associated. Could you try tainting the `random_project_id_suffix`. You should see those resources if you do a `terraform state list`.

**Comment by jamesvnz** [comment]
I had the same issue, and overcame it with tainting the suffix as suggested. It wasn't clear to me how to easily do this when the plan / apply was being run on Cloud Build. My solution was as follows:

```
 gsutil cp gs://<remote-state-bucket-name>/terraform/org/state/default.tfstate .
 terraform taint module.scc_notifications.module.project-factory.random_id.random_project_id_suffix -state=default.tfstate
gsutil cp default.tfstate  gsutil cp gs://<remote-state-bucket-name>/terraform/org/state/default.tfstate

```
I'm not sure if this is the correct way to fix this kind of issue. Perhaps this (or the correct way to do this) should be in the troubleshooting docs?

**Comment by gjj** [comment]
@bharathkkb thanks for that! Wish I knew that earlier because I've faced a similar issue and did `terraform destroy` as described in https://github.com/terraform-google-modules/terraform-example-foundation/issues/378#issuecomment-859353314

Actually it seems like it's a very common issue - do you think it's possible to leave a note somewhere early (e.g. in 0-bootstrap or 1-org) saying that users may need to request for additional quota?

**Comment by bharathkkb** [comment]
Hi @gjj @jamesvnz 

I have an open issue to add this to our troubleshooting doc https://github.com/terraform-google-modules/terraform-example-foundation/issues/451. @jamesvnz  solution is correct, there is no easy way to do this via CloudBuild. If you have bandwidth we are happy to review a PR to add this. Closing this now to track in the parent issue.
