### ISSUE TITLE
1-ORG Error 409: Sink sk-c-logging-bq already exists

### ISSUE THREAD

**Issue by JuvenalRz** [terraform-google-modules/terraform-example-foundation#495]
Hello!

Anyone here can help me?

I was trying to get a success deploy of 1-ORG but I get errors please see the image below:
![Captura](https://user-images.githubusercontent.com/86978869/124504313-d1cd8880-dd8c-11eb-8d5a-c4fe33e3e86e.PNG)

![imagen](https://user-images.githubusercontent.com/86978869/124504322-d98d2d00-dd8c-11eb-88bf-79dd7951e6db.png)

**Comment by jamesvnz** [comment]
Check that the Project hasn't actually been created (you should see it in the list of "all" projects). If it's not there, then the likely cause is the random project suffix is making the code thing that it is. This is the same issue as #494

**Comment by JuvenalRz** [comment]
> 
> 
> Check that the Project hasn't actually been created (you should see it in the list of "all" projects). If it's not there, then the likely cause is the random project suffix is making the code thing that it is. This is the same issue as #494

Actually I delete all the folders and projects and begin but I'm still having the issue, I don´t understand why?

**Comment by bharathkkb** [comment]
@JuvenalRz This looks like an org level log sink. Does `gcloud logging sinks list --organization=$ORG_ID` show any existing?

**Comment by JuvenalRz** [comment]
> gcloud logging sinks list --organization=$ORG_ID

This is what it shows when I run the command :

**Comment by JuvenalRz** [comment]
Hello!

I'm still stucked with this issue, anyone can help me?

**Comment by aarturm** [comment]
It looks like someone already deployed terraform-example-foundation in your organization. Try to find out owner of prj-c-logging-6dc1 project. If those are some leftovers from your (or someone else) tests you have to clean that up. I guess best would be to run terraform destroy on that previous deployment.  
If that previous deployment is needed you can deploy in a folder if that suits your needs.

**Comment by JuvenalRz** [comment]
> It looks like someone already deployed terraform-example-foundation in your organization. Try to find out owner of prj-c-logging-6dc1 project. If those are some leftovers from your (or someone else) tests you have to clean that up. I guess best would be to run terraform destroy on that previous deployment.
> If that previous deployment is needed you can deploy in a folder if that suits your needs.

How can do that? If I delete everything one by one and don't use terraform destroy :/

**Comment by JuvenalRz** [comment]
![imagen](https://user-images.githubusercontent.com/86978869/126494244-0f72f8e9-a3a6-45ef-ad66-e2ad242b612a.png)

At this moment its the only thing that appears

**Comment by aarturm** [comment]
You can try doing deployment now and remove existing resources in case you see another 'already exists' error. 
If you want to use terraform destroy you need to:
- go to folder with the code (for example envs/shared for 1-org step)
- update backend.tf with bucket with terraform tfstate
- run terraform init  and terraform destroy.
That should work if you still have tfstate file and didn't remove resources. 
It worked for me for some steps but not all. It think it did proper cleanup for org step.

**Comment by JuvenalRz** [comment]
> 
> 
> You can try doing deployment now and remove existing resources in case you see another 'already exists' error.
> If you want to use terraform destroy you need to:
> 
>     * go to folder with the code (for example envs/shared for 1-org step)
> 
>     * update backend.tf with bucket with terraform tfstate
> 
>     * run terraform init  and terraform destroy.
>       That should work if you still have tfstate file and didn't remove resources.
>       It worked for me for some steps but not all. It think it did proper cleanup for org step.

I'll try, thank you for your help.
