### ISSUE TITLE
Question on deploying GKE cluster onto 5-app-infra

### ISSUE THREAD

**Issue by gjj** [terraform-google-modules/terraform-example-foundation#496]
Hello! If I wanted to deploy e.g. a GKE cluster using [terraform-google-modules/kubernetes-engine/google](https://registry.terraform.io/modules/terraform-google-modules/kubernetes-engine/google/latest), is there anything I should take note of?

Currently, deploying a simple GCE instance works for me, but not for a GKE cluster as I seem to get the permissions issue error:
```
Error: converting tfplan to CAI assets: adding resource changes to converter: adding resource create or update augmenting asset: getting resource ancestry: project prj-bu2-d-sample-base-xxxx googleapi: Error 403: The caller does not have permission
```
Here's what I've already tried
* I tried looking this up on Search but wasn't able to find any useful info
* I've also tried granting `roles/owner` and `roles/iam.serviceAccountTokenCreator` to the Business Unit infra pipeline's project service account but still got the same error 403.

I tested the [same GKE script I created](https://github.com/bankoncloud/examples/blob/main/gke-bank-of-anthos/main.tf) on my org's `My First Project` (i.e. not part of the folders where the cloud security foundation's org policies are applied) and everything works, just not (i.e. Error 403) when it's passed through the `terraform-validator`.

Is it because I should be relaxing some constraints in the app's `policy-library`?

**Comment by rajesh-nitc** [comment]
May be this could help https://github.com/rajesh-nitc/gcp-foundation

**Comment by gjj** [comment]
> May be this could help https://github.com/rajesh-nitc/gcp-foundation

Thanks! Will take a look.

**Comment by bharathkkb** [comment]
Hi @gjj 
You can take a look at https://github.com/GoogleCloudPlatform/terraform-example-foundation-app for how to deploy GKE on top of example-foundation (5-infrastructure section). We also have a [section](https://github.com/GoogleCloudPlatform/terraform-example-foundation-app/tree/main/5-infrastructure#setup-to-run-via-cloud-build) there on how to manage validator policies for private GKE clusters. Feel free to reopen if any issues.
