### ISSUE TITLE
Error in module "scc_notification"

### ISSUE THREAD

**Issue by jkrueger-jaconi** [terraform-google-modules/terraform-example-foundation#506]
I am seeing issues within the 1-org section when trying to setup the scc notification. The gcloud command call errors out with

```
│ Error: local-exec provisioner error
│ 
│   with module.scc_notification.null_resource.run_command[0],
│   on .terraform/modules/scc_notification/main.tf line 220, in resource "null_resource" "run_command":
│  220:   provisioner "local-exec" {
│ 
│ Error running command
│ 'PATH=/workspace/.terraform/modules/scc_notification/cache/8d2d837d/google-cloud-sdk/bin:$PATH
│ gcloud scc notifications create scc-notify --organization XXXXXXXXXX \
│ --description "SCC Notification for all active findings" \
│ --pubsub-topic projects/prj-scc-XXXX/topics/top-scc-notification \
│ --filter "state=\"ACTIVE\"" \
│ --project "prj-scc-XXXX" \
│ --impersonate-service-account=org-terraform@prj-seed-XXXX.iam.gserviceaccount.com
│ 
│ ': exit status 1. Output: WARNING: This command is using service account
│ impersonation. All API calls will be executed as
│ [org-terraform@prj-seed-XXXX.iam.gserviceaccount.com].
│ WARNING: This command is using service account impersonation. All API calls
│ will be executed as [org-terraform@prj-seed-XXXX.iam.gserviceaccount.com].
│ ERROR: (gcloud.scc.notifications.create) INVALID_ARGUMENT: Request contains
│ an invalid argument.
│ 
```

Testing the command locally, it seems to not like the `--project` argument.

**Comment by bharathkkb** [comment]
Hi @jkrueger-jaconi 
Thanks for the report. Whats the output locally with the command?

**Comment by bharathkkb** [comment]
Also wondering if you could check via the UI to select a tier first (standard should work)

https://cloud.google.com/security-command-center/docs/quickstart-security-command-center#select-tier

**Comment by jkrueger-zageno** [comment]
> Also wondering if you could check via the UI to select a tier first (standard should work)
> 
> https://cloud.google.com/security-command-center/docs/quickstart-security-command-center#select-tier

Uhhh... I totally messed that one up. Activated on the wrong org 🙄 

Selecting the tier in the correct org fixed it. Wish the cli would be a bit more specific when erroring out. But again, totally my fault.

@bharathkkb Please close and thanks a lot!

**Comment by bharathkkb** [comment]
@jkrueger-jaconi I'll open a bug internally to track a better error message.
