### ISSUE TITLE
In scc_notification.tf "gcloud scc notifications create" gives INVALID_ARGUMENT error

### ISSUE THREAD

**Issue by aitchpea** [terraform-google-modules/terraform-example-foundation#510]
In file https://github.com/terraform-google-modules/terraform-example-foundation/blob/master/1-org/envs/shared/scc_notification.tf 

I get the following error:
ERROR: (gcloud.scc.notifications.create) INVALID_ARGUMENT: Request contains an invalid argument.

The command being invoked is:
 gcloud scc notifications create scc-notify --organization 71228XXXX \
--pubsub-topic projects/prj-c-scc-xxxx/topics/top-scc-notification \
--filter="state=\"ACTIVE\"" \
--project "prj-c-scc-xxxx" \
--impersonate-service-account "org-terraform@prj-b-seed-xxxx.iam.gserviceaccount.com"

![image](https://user-images.githubusercontent.com/83715131/126766522-49e76e3a-d680-44cd-845a-26078b783c24.png)

I have checked:
* the project exists (it does)
* the pubsub topic does exist (see picture below)
* I have run the gcloud call from the console and get the same error - and tried changing or removing parameters to work out which is invalid (to no avail)
* I have removed the impersonate-serv-acct call (and given myself the relevant security role) and still get the same error
* I can see the version of the module being used is "~>1.1.0" and this is quite far behind the latest version (3.0.0) so I have tried upgrading this to use 3.0.0 and get the same error

![image](https://user-images.githubusercontent.com/83715131/126767162-72e5efdb-ae10-4551-b65a-ee67c1a523b3.png)

Looking at the documentation on https://registry.terraform.io/modules/terraform-google-modules/gcloud/google/latest I cannot see anything standing out as being wrong with the parameters supplied.

I am using TF 1.0.0 (which is clearly > v0.12 as specified in https://registry.terraform.io/modules/terraform-google-modules/gcloud/google/latest) so it might be that you wish that all users use this old version of TF?

Depending on the outcome and the cause of the error I am also keen to know where I could raise an issue for gcloud as I don't think that an error message saying "you have an invalid parameter but I won't tell you which one or what is wrong" isn't how I envisaged errors being reported.

**Comment by aitchpea** [comment]
Ok - so I understand the cause of my issue, it is because I had not completed step 4 in the Pre-Requisites for 1-Org

![image](https://user-images.githubusercontent.com/83715131/126796526-6ce8e10f-934b-40dc-a046-2ad101661656.png)

[I do think the documentation could be a lot clearer - ideally with a simple youtube video + I am not impressed with the error message, but c'est la vie]

**Comment by bharathkkb** [comment]
Thanks for the report, I have opened a bug with a fix coming soon
