### ISSUE TITLE
(TF 1.0 question) for 3-networks in dns.tf "Error: Missing required argument"

### ISSUE THREAD

**Issue by aitchpea** [terraform-google-modules/terraform-example-foundation#512]
I know that you are only now considering updating terraform-google-modules to be the newer version (and also for TF 1.0 rather than 0.13 through 0.15) so this question might be premature or considered impolite to ask yet.

Summary: I have used TF 1.0 to perform 0-bootstrap through 2-environments and now onto 3-networks. Immediately I hit the issue that some of these older dependent modules are not supporting anything > 0.15, e.g.

![image](https://user-images.githubusercontent.com/83715131/126880752-2cb38dea-bf75-44ac-933d-2b7c52d7ff2d.png)

so I went through a number of the files updating them to the latest available versions in Terraform Registry. (I can supply these details but right now I think that might cloud the error message below)

I have now hit an error that I am having trouble understanding (and therefore how to fix)

In file https://github.com/terraform-google-modules/terraform-example-foundation/blob/master/3-networks/modules/base_shared_vpc/dns.tf 

there is the peering zone block

![image](https://user-images.githubusercontent.com/83715131/126880785-89ae8c46-5229-45da-852c-f5a0bbc83a64.png)

which gives the following error when doing a "terraform apply":

![image](https://user-images.githubusercontent.com/83715131/126880804-2af1da13-93f1-4b01-9011-7ec4362f752a.png)

I am having trouble getting my head around the actual error to understand if it is a syntax issue somewhere or an invalid module or something else has changed??

**Comment by bharathkkb** [comment]
Hi @aitchpea 

Could you confirm that you ran the [shared](https://github.com/terraform-google-modules/terraform-example-foundation/tree/master/3-networks/envs/shared) config first? We do a[ lookup for the vpc](https://github.com/terraform-google-modules/terraform-example-foundation/blob/ed164ba7139e1aec39f8e9f37e9ac915e8afaa8c/3-networks/modules/base_shared_vpc/dns.tf#L34) and I think that maybe returning empty. You can also check by adding an extra output in the config and checking that this returns a valid self_link

```
output "check_vpc_dns_hub" {
  value       = data.google_compute_network.vpc_dns_hub.self_link
}
```

Also using the DNS module with 1.0 you may run into https://github.com/terraform-google-modules/terraform-google-cloud-dns/issues/30 suggest using 0.15 until we cut that upstream release or using the `main` branch.

**Comment by aitchpea** [comment]
You are correct - I had not run the shared config first, so that is going to be the issue. I had planned to run it and then be able to say that it 100% works but I have not yet completed it (but have confidence that what you say is the solution).

(I shall watch out for the issue you mention as I move forward)

Thanks for your help

**Comment by aitchpea** [comment]
Apols - I had meant to close the issue with the previous comment..
