### ISSUE TITLE
Shared VPC Build

### ISSUE THREAD

**Issue by langleyce** [terraform-google-modules/terraform-example-foundation#52]
Why? To align existing foundations example with the best practice whitepaper guidance.
Updates:
- Per environment(x?)
  - Shared VPC
    - base
      - subnet region 1
      - subnet region 2
      - cloud router 1(x2)
      - cloud router 2(x2)
      - firewall rules (?)
      - cloud DNS
    - restricted
      - subnet region 1
      - subnet region 2
      - cloud router 1(x2)
      - cloud router 2(x2)
      - firewall rules (?)
      - cloud DNS    
- DNS Hub project(peered cloud DNS)
- Interconnect Attachment(x?)

**Comment by morgante** [comment]
This should be done per environment. In particular:

- Create the host project(s) for each environment in 2-environments (see #51)
- Create the actual network resources for each environment in 3-networks

**Comment by rjerrems** [comment]
I have also started part the work for the host project side of things here:

https://github.com/terraform-google-modules/terraform-example-foundation/pull/53

**Comment by bharathkkb** [comment]
@daniel-cit I  think with the last `DNS Hub project` PR this is complete?

**Comment by rjerrems** [comment]
Completed with this PR https://github.com/terraform-google-modules/terraform-example-foundation/pull/79
