### ISSUE TITLE
Create a Jenkins pipeline incorporating terraform-validator

### ISSUE THREAD

**Issue by bharathkkb** [terraform-google-modules/terraform-example-foundation#54]
Create Jenkins pipeline which does the following
- `terraform init`
- `terraform plan -out terraform.tfplan && terraform show -json ./terraform.tfplan > ./terraform.tfplan.json`
-  `terraform-validator validate --policy-path=${POLICY_PATH} ./terraform.tfplan.json`
- `terraform apply ./terraform.tfplan`

We can start with this [Jenkinsfile](https://github.com/GoogleCloudPlatform/solutions-terraform-jenkins-gitops/blob/master/example-pipelines/environments/Jenkinsfile) which already does `init`, `plan` and `apply`; modify as needed for working with GCE. Jenkins worker will be a GCE VM and we can assume terraform and [terraform-validator](https://github.com/GoogleCloudPlatform/terraform-validator) binaries will be installed on this worker.

Validation: 
A simple validation can be

- Set up policies such that GCE VMs cannot be launched with external IPs, i.e terraform-validator stage catches this and fails.

**Comment by xingao267** [comment]
why not use cloud build for this?

**Comment by bharathkkb** [comment]
@xingao267 this is part of whitepaper effort where Jenkins is used but I believe this is easy enough to cross port to CB. 
/cc @mikelaramie & @langleyce

**Comment by ipv1337** [comment]
Are you going to use Jenkins X for this pipeline? I was hoping to tie these examples together with Jenkins X and or Cloud Build so the example can expand beyond the opinionated project structure.

**Comment by rjerrems** [comment]
@ipv1337 we are currently looking to support standard Jenkins and Cloud Build as a part of the effort @bharathkkb mentioned. Are you looking to implement `terraform-validator` in your workflow?

**Comment by nhsy** [comment]
I’ve been experimenting with terraform-validator and Cloudbuild, example below:

https://github.com/nhsy/gcp-terraform-validator

**Comment by bharathkkb** [comment]
fixed via #109 #157
