### ISSUE TITLE
Access denied for fldr-development resource

### ISSUE THREAD

**Issue by vortex-abdel-toukebri** [terraform-google-modules/terraform-example-foundation#542]
Hello!
The project service account created on step 4-projects for the sample base project in the development environment has access denied error when used on step 5-app-infra despite the Browser Role granted on `fldr-development` folder. Bellow is a sample of the same errors I got during terraform plan:

```
Error: Error when reading or editing Folder Not Found : fldr-development: Post "https://cloudresourcemanager.googleapis.com/v2/folders:search?alt=json&prettyPrint=false": impersonate: status code 403: {
  "error": {
    "code": 403,
    "message": "The caller does not have permission",
    "status": "PERMISSION_DENIED"
  }
}

on folder.tf line 17, in data "google_active_folder" "env":
17: data "google_active_folder" "env" {
```

**Comment by bharathkkb** [comment]
Hi @vortex-abdel-toukebri 
If you are running `5-app-infra` locally your user account needs to have `Service Account Token Creator` on the `project_service_account ` created in 4-projects. Feel free to reopen if still an issue.
