### ISSUE TITLE
[UX]: Root readme should call out supported/tested platforms for sample commands

### ISSUE THREAD

**Issue by philip-harvey** [terraform-google-modules/terraform-example-foundation#545]
Many of the readme files assume a Linux platform.  e.g. the copy commands, chmod, etc.
The readme files could be more platform agnostic.  e.g. use ``git update-index --chmod=+x``
Alternatively the root readme could set out supported/tested platforms.

**Comment by bharathkkb** [comment]
Thanks for report @pharveybattelle 
Currently we dont have plans for an alternate readme, but will call this out as a prerequisite.
