### ISSUE TITLE
Error retrieving IAM policy for organization "XXXXXXX": googleapi: Error 403: The caller does not have permission, forbidden

### ISSUE THREAD

**Issue by sganesanmuth** [terraform-google-modules/terraform-example-foundation#558]
Hi @bharathkkb 

As I followed the steps as mentioned in the doc, am getting below error when I try to push the code into gcp-org repo in GCP Cloud Source and below is the error message from the Cloud build (i.e. gcp-org---terraform-plan Cloud Build trigger). Any clue, how to resolve this issue. Thanks!

Step #1 - "tf plan validate all": This plan was saved to: /workspace/tmp_plan/envs-shared.tfplan
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": To perform exactly these actions, run the following command to apply:
Step #1 - "tf plan validate all":     terraform apply "/workspace/tmp_plan/envs-shared.tfplan"
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": *************** TERRAFORM VALIDATE ******************
Step #1 - "tf plan validate all":       At environment: envs/shared 
Step #1 - "tf plan validate all":       Using policy from: /workspace/policy-library 
Step #1 - "tf plan validate all": *****************************************************
Step #1 - "tf plan validate all": WARNING: This command is using service account impersonation. All API calls will be executed as [org-terraform@prj-b-seed-64ba.iam.gserviceaccount.com].
Step #1 - "tf plan validate all": WARNING: This command is using service account impersonation. All API calls will be executed as [org-terraform@prj-b-seed-64ba.iam.gserviceaccount.com].
Step #1 - "tf plan validate all": WARNING: This command is using service account impersonation. All API calls will be executed as [org-terraform@prj-b-seed-64ba.iam.gserviceaccount.com].
Step #1 - "tf plan validate all": Cloning into '/workspace/policy-library'...
Step #1 - "tf plan validate all": WARNING: This command is using service account impersonation. All API calls will be executed as [org-terraform@prj-b-seed-64ba.iam.gserviceaccount.com].
Step #1 - "tf plan validate all": Project [prj-b-cicd-142f] repository [gcp-policies] was cloned to [/workspace/policy-library].
Step #1 - "tf plan validate all": ERROR: logging before flag.Parse: I0909 16:36:02.776621     455 convert.go:213] unsupported resource: google_folder
Step #1 - "tf plan validate all": ERROR: logging before flag.Parse: I0909 16:36:02.776666     455 convert.go:213] unsupported resource: google_folder_iam_audit_config
Step #1 - "tf plan validate all": ERROR: logging before flag.Parse: I0909 16:36:02.776680     455 convert.go:207] unknown resource: google_scc_notification_config
Step #1 - "tf plan validate all": ERROR: logging before flag.Parse: I0909 16:36:02.776692     455 convert.go:213] unsupported resource: google_billing_budget
.......
Step #1 - "tf plan validate all": ERROR: logging before flag.Parse: I0909 16:36:02.777177     455 convert.go:207] unknown resource: random_string
**_Step #1 - "tf plan validate all": Error: converting tfplan to CAI assets: adding resource changes to converter: adding resource create or update fetching asset: Error retrieving IAM policy for organization "XXXXXXX": googleapi: Error 403: The caller does not have permission, forbidden_**
Step #1 - "tf plan validate all": Usage:
Step #1 - "tf plan validate all":   terraform-validator validate <tfplan> [flags]
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": Flags:
Step #1 - "tf plan validate all":       --ancestry string      Override the ancestry location of the project when validating resources
Step #1 - "tf plan validate all":   -h, --help                 help for validate
Step #1 - "tf plan validate all":       --offline              Do not make network requests
Step #1 - "tf plan validate all":       --output-json          Print violations as JSON
Step #1 - "tf plan validate all":       --policy-path string   Path to directory containing validation policies
Step #1 - "tf plan validate all":       --project string       Provider project override (override the default project configuration assigned to the google terraform provider when validating resources)
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": Global Flags:
Step #1 - "tf plan validate all":       --verbose   Log output to stderr
Step #1 - "tf plan validate all":

**Comment by jaroslawgajewski** [comment]
are you using master branch for deployment or version 2.2.0?

**Comment by sganesanmuth** [comment]
Am using a master branch.

**Comment by jaroslawgajewski** [comment]
please add Security Reviewer role for you cloud build service account as terraform validator 0.4.0 is not supporting account impersonation and current master branch do not have 0.7.0 yet

**Comment by sganesanmuth** [comment]
Thanks for your response. Am still facing the same issue though I've added the "Security Reviewer" role to Cloud Build Service Account.

**Comment by bharathkkb** [comment]
Hi @sganesanmuth could you confirm that you added "Security Reviewer" role to Cloud Build Service Account at the org level?

**Comment by sganesanmuth** [comment]
@bharathkkb - Yes, I confirm that I added the "Security Reviewer" role to Cloud Build Service Account at the org level. Refer the screen shot.
<img width="1000" alt="Screen Shot 2021-09-15 at 8 12 32 AM" src="https://user-images.githubusercontent.com/7253892/133362326-513e9314-9504-4466-ba49-e4ac5e2585e4.png">

**Comment by bharathkkb** [comment]
@sganesanmuth it should be added to the default Cloud Build Service Account (it will be of form `PROJECT_NUM@cloudbuild.gserviceaccount.com`). You can find this SA in the `cicd` project. TFV doesn't currently support SA impersonation which is why we need to add this to the CB SA.

**Comment by sganesanmuth** [comment]
@bharathkkb - Thanks for your help. Now its working fine without any error after adding the "Security Reviewer" role to Cloud Build Service Account at the org level as you mentioned.
