### ISSUE TITLE
Unable to delete fldr-common

### ISSUE THREAD

**Issue by barumugham** [terraform-google-modules/terraform-example-foundation#591]
I am trying to clean up the resources after building the foundation till step 4, I am able to delete all the resources. the only remaining folder is **fldr-common** which i have deleted all the projects inside that and now it is empty , but when I try to delete it it tells "**Folder cannot be deleted as it contains active resources**". I check there are no resources inside that
gcloud projects list --filter="parent.id:684172463136"
Listed 0 items.

gcloud resource-manager folders list --folder=684172463136
Listed 0 items.

gcloud beta resource-manager org-policies list --folder=684172463136
Listed 0 items.

I also followed this post: 
https://stackoverflow.com/questions/67705683/gcp-folder-cannot-be-deleted-as-it-contains-active-resources

but still i am not finding a solution and unable to delete it. Can you please help me with the steps?

**Comment by daniel-cit** [comment]
Hi @barumugham , the resource your are looking for is an [Hierarchical firewall policy](https://cloud.google.com/vpc/docs/firewall-policies) created in the common folder.

Go to the page https://console.cloud.google.com/networking/firewalls/list?folder=<YOUR-COMMON-FOLDER-ID>
and you will see the firewall rules. 

You will need to delete the associations of the firewall rules with the folders create in the foundation before deleting the rules.

**Comment by barumugham** [comment]
Thank you @daniel-cit it worked
