### ISSUE TITLE
Remind users to use ADC for bootstrap

### ISSUE THREAD

**Issue by bharathkkb** [terraform-google-modules/terraform-example-foundation#606]
### TL;DR

We should remind users to confirm they are authed via `gcloud auth application-default login` as bootstrap is manual.

### Terraform Configuration

```hcl
N/A
```

### Terraform Version

```sh
N/A
```

**Comment by cosminonea** [comment]
I am trying to understand what the minimum amount of stuff that needs creating is before I can run the bootstrap. What is not clear to me is if I need a project and a service account to be manually created.

If I just have the org with no projects, run `gcloud auth application-default login` and then run terraform I get this (the main org groups are the first thing I am creating):

> Error: Error creating Group: googleapi: Error 403: Your application has authenticated using end user credentials from the Google Cloud SDK or Google Cloud Shell which are not supported by the cloudidentity.googleapis.com. We recommend configuring the billing/quota_project setting in gcloud or using a service account through the auth/impersonate_service_account setting. For more information about service accounts and how to use them in your application, see https://cloud.google.com/docs/authentication/. If you are getting this error with curl or similar tools, you may need to specify 'X-Goog-User-Project' HTTP header for quota and billing purposes. For more information regarding 'X-Goog-User-Project' header, please check https://cloud.google.com/apis/docs/system-parameters.

**Comment by cosminonea** [comment]
An initial project is required for quota and billing. It could be any.

To be able to run the bootstrap with application default credentials I had to set the provider app like this:

```
provider "google" {
  region = "europe-west2"
  billing_project = "my-project-123"
  user_project_override = true
}
```
Overriding the `billing_project` and setting the user_project_override got rid of the 403 errors.

**Comment by Extrunder** [comment]
This is important reminder, spend a couple of hours to figure it out!
