### ISSUE TITLE
Why not use trunk based development?

### ISSUE THREAD

**Issue by fernando-villalba** [terraform-google-modules/terraform-example-foundation#607]
The [branching strategy ](https://github.com/terraform-google-modules/terraform-example-foundation#branching-strategy)suggested is not trunk based development, from previous experience, working with multiple long lived branches can become messy.

Also trunk based development is [heavily recommended by google ](https://cloud.google.com/architecture/devops/devops-tech-trunk-based-development)as a best practice

Not judging here, just trying to understand, Is there any particular reason why this was chosen over TBD?

**Comment by bharathkkb** [comment]
Hi @fernando-villalba 
We suggested this env branch strategy based on being able to gate config promotion across environments easily via PRs. A trunk based workflow can also be easily realized by adding [some additional logic](https://github.com/terraform-google-modules/terraform-example-foundation/blob/master/build/tf-wrapper.sh) to your deployments and gating with [comprehensive codeowners file ](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#example-of-a-codeowners-file)as supported by your VCS. Feel free to reopen if you need any additional clarification.
