### ISSUE TITLE
Hardcoded labels in 0-bootstrap, should be variables. 

### ISSUE THREAD

**Issue by haggman** [terraform-google-modules/terraform-example-foundation#636]
### TL;DR

Running through 0-bootstrap and was surprised to see the project labels on the seed and cicd projects. I get that the foundation blueprint recommends these particular labels, but I see no reason why changing them should require editing the root terraform module for 0-bootstrap's main.tf file, in two distinct sections. Make these variables. Also, update the docs to reflect them. 

### Terraform Resources

0-bootstrap's main.tf, variables.tf, and readme

**Comment by morgante** [comment]
The example foundation is designed to be a *starting point* for your own configuration. That's why one of the first steps we tell you to take is forking it into your own Git repo.

Editing the `main.tf` is expected behavior and exactly how we expect you to take the code and make it your own.
