### ISSUE TITLE
Use Private Service Connect instead of Private Google Access

### ISSUE THREAD

**Issue by langleyce** [terraform-google-modules/terraform-example-foundation#673]
### TL;DR

Size: TBD

**Comment by bharathkkb** [comment]
https://cloud.google.com/vpc/docs/configure-private-service-connect-apis

**Comment by bharathkkb** [comment]
This can be implemented as an inline module for networking stage, upstreamed to CFT networking module later

**Comment by daniel-cit** [comment]
closed by #722

**Comment by daniel-cit** [comment]
closed by https://github.com/terraform-google-modules/terraform-example-foundation/pull/722
