### ISSUE TITLE
Enable Essential Contacts

### ISSUE THREAD

**Issue by langleyce** [terraform-google-modules/terraform-example-foundation#683]
### TL;DR

Size: TBD
https://github.com/terraform-google-modules/terraform-google-project-factory/tree/master/modules/essential_contacts

**Comment by bharathkkb** [comment]
Bump PF versions to https://github.com/terraform-google-modules/terraform-google-project-factory/releases/tag/v12.0.0

**Comment by bharathkkb** [comment]
@LuizSDCit also pointed out that essential contacts are available at Folder/Org level. In addition to allowing per project essentials contacts, we could map some of our [existing groups](https://github.com/terraform-google-modules/terraform-example-foundation/blob/3f61dbaab143d5ca2fdaebb53bb4f858ac4218a8/1-org/envs/shared/variables.tf#L295-L347) to notification configs.

Some initial ideas:
- gcp_security_reviewer, gcp_scc_admin -> Security, Legal
- gcp_billing_creator_user -> Billing
- gcp_org_admin_user -> Suspension

https://cloud.google.com/resource-manager/docs/managing-notification-contacts#notification-categories for full list
