### ISSUE TITLE
Terraform Validator testing in CI

### ISSUE THREAD

**Issue by langleyce** [terraform-google-modules/terraform-example-foundation#691]
### TL;DR

Size: L

**Comment by daniel-cit** [comment]
This issue depends on issue https://github.com/terraform-google-modules/terraform-example-foundation/issues/608 to be fixed

**Comment by daniel-cit** [comment]
This should use [gcloud beta terraform vet](https://cloud.google.com/docs/terraform/policy-validation/quickstart)

**Comment by bharathkkb** [comment]
fixed by https://github.com/terraform-google-modules/terraform-example-foundation/pull/779
