### ISSUE TITLE
Cloud Build for "2-environments" step (develop branch)

### ISSUE THREAD

**Issue by kadodson612** [terraform-google-modules/terraform-example-foundation#70]
@bharathkkb 

Suggestion for Cloud Build config - "2-environments" step (terraform-example-foundation develop branch)

1. Create Cloud Build configuration files that run `terraform init`, `terraform plan`, and `terraform apply` for each of the environments (dev, prod, nonprod) 

2. Within Bootstrap, provision empty gcp-envs CSR (Cloud Source Repository) in Cloud Build Project with proper triggers, variables (see gcp-org repository for reference). This can be used for Cloud Build in "2-environments" step.

3. Change README documentation to reflect changes

**Comment by bharathkkb** [comment]
We should follow the general approach here https://github.com/terraform-google-modules/terraform-example-foundation/issues/47#issuecomment-638953590
/cc @rjerrems  @mikelaramie  @langleyce  this would be part of the wrapper script we discussed.

**Comment by rjerrems** [comment]
Fixed by https://github.com/terraform-google-modules/terraform-example-foundation/pull/111
