### ISSUE TITLE
unsupported version?? can anyone please guide me urgently?

### ISSUE THREAD

**Issue by RickyDev0p** [terraform-google-modules/terraform-example-foundation#795]
why "terraform console" not supported in version 1.2.8
Error: Unsupported Terraform Core version
│
│ on c1-versions.tf line 3, in terraform:
│ 3: required_version = "~> 0.14" # which means any version equal & above 0.14 like 0.15, 0.16 etc and < 1.xx
│
│ This configuration does not support Terraform version 1.2.8 To proceed, either choose another supported Terraform
│ version or update this version constraint. Version constraints are normally set for good reason, so updating the
│ constraint may lead to other errors or unexpected behavior.

**Comment by bharathkkb** [comment]
@RickyDev0p Did you get an error from this repo? I am not aware of a file like `c1-versions.tf` in our codebase and we only require >=0.13 without an upper bound.
