### ISSUE TITLE
Try testing only one env in e2e build

### ISSUE THREAD

**Issue by bharathkkb** [terraform-google-modules/terraform-example-foundation#801]
### TL;DR

Between overall validate and usage of base_env, even deploying 1 env should given us expected e2e confidence. @daniel-cit mentioned an improvement of 30-40 mins and we can likely also reduce flakes.

**Comment by daniel-cit** [comment]
to be able to test only one environment it is still necessary to create a unified shared env module for the 4-projects [bu1 shared](https://github.com/terraform-google-modules/terraform-example-foundation/tree/master/4-projects/business_unit_1/shared) and [bu2 shared](https://github.com/terraform-google-modules/terraform-example-foundation/tree/master/4-projects/business_unit_2/shared) environments.

**Comment by eeaton** [comment]
I'm cleaning up old issues, this has also come up in #1238 so I'll close this old issue as a duplicate of the newer issue which has some additional details.
