### ISSUE TITLE
Use terraform remote state in step 5-app-infra to read data from previous steps

### ISSUE THREAD

**Issue by daniel-cit** [terraform-google-modules/terraform-example-foundation#809]
### TL;DR

Use terraform [remote state](https://www.terraform.io/language/state/remote-state-data) in step 5-app-infra to read 

- `org_id`
- `instance_region`
- `parent_folder`
- Development `project_service_account`
- Non-Production `project_service_account`
- Production `project_service_account`

from previous steps

**Comment by bharathkkb** [comment]
Since the amount of details needed from other stages are limited, an approach could be to add a new config output in 4-projects (for org_id, folder etc) for 5-app-infra to read from. This would obviate the need for reader access to all the other stage backends.
