### ISSUE TITLE
Add a repo for bootstap 

### ISSUE THREAD

**Issue by bharathkkb** [terraform-google-modules/terraform-example-foundation#817]
### TL;DR

We should encourage storing bootstrap stage source code in a source repo similar to other stages to be managed by cloudbuild after bootstrap.

**Comment by daniel-cit** [comment]
Hi @bharathkkb we have a repo for bootstrap

https://github.com/terraform-google-modules/terraform-example-foundation/blob/da36150707b1e7f979035eb6bc47e04b2df88a5c/0-bootstrap/cb.tf#L34

we need to add instructions in the 0-bootstrap README on how to save the code in this repo after the deploy
