### ISSUE TITLE
Add real app example

### ISSUE THREAD

**Issue by guissalustiano** [terraform-google-modules/terraform-example-foundation#862]
### TL;DR

Currently the last layer has only one virtual machine, however in real applications it is more complicated than that.
I believe it is important to create a more robust example at the end to close the example with a flourish.

### Detailed design

```markdown
I thought of putting an example with a public machine and a private database, but I don't know the best way to extend
Would they be on the same project?
The machine would be in the base-shared VPC and the bank in the base-restricted? Would I connect the two with VPC peering?
```

**Comment by rajesh-nitc** [comment]
Please check if this is of any help https://github.com/rajesh-nitc/gcp-foundation
